### PR TITLE
std:__1:string fix for AIX

### LINKED ISSUE #76: string member of class is not printed
c++ program:-
==============
#include <iostream>
class Person {
public:
    std::string name;
    int age;
    double height;
    Person(const std::string& n, int a, double h) : name(n), age(a), height(h) {}
};
int main() {
    Person p("Alice", 30, 1.65);

    // ...

    return 0;

}

/opt/IBM/openxlC/17.1.2/bin/ibm-clang++_r -o fresh fresh.cpp -m64 -g

Logs(aix-lldb):-
---------------
# ./lldb fresh
(lldb) target create "fresh"
Current executable set to '/home/LLDB/package/aix-pre-release-0.4.x/bin/fresh' (powerpc64).
(lldb) b main
Breakpoint 1: where = fresh`main + 28 at fresh.cpp:10, address = 0x000000010000093c
(lldb) r
Process 15204610 launched: '/home/LLDB/package/aix-pre-release-0.4.x/bin/fresh' (powerpc64)
Process 15204610 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x000000010000093c fresh`main at fresh.cpp:10
   7   	    Person(const std::string& n, int a, double h) : name(n), age(a), height(h) {}
   8   	};
   9   	int main() {
-> 10  	    Person p("Alice", 30, 1.65);
   11
   12  	    // ...
   13
(lldb) n
Process 15204610 stopped
* thread #1, stop reason = step over
    frame #0: 0x000000010000097c fresh`main at fresh.cpp:14
   11
   12  	    // ...
   13
-> 14  	    return 0;
   15
   16  	}
(lldb) print p
(Person)  (name = Summary Unavailable, age = 30, height = 1.6499999999999999) ======>>>> name is not printed here
(lldb) q
Quitting LLDB will kill one or more processes. Do you really want to proceed: [Y/n] y

logs(linux-lldb)
---------------
lldb) target create "fresh"
Current executable set to '/home/fresh' (x86_64).
(lldb) b main
Breakpoint 1: where = fresh`main + 9 at fresh.cpp:21:31, address = 0x00000000004009cf
(lldb) r
Process 60060 launched: '/home/fresh' (x86_64)
Process 60060 stopped
* thread #1, name = 'fresh', stop reason = breakpoint 1.1
    frame #0: 0x00000000004009cf fresh`main at fresh.cpp:21:31
   18
   19  	int main() {
   20
-> 21  	    Person p("Alice", 30, 1.65);
   22
   23  	    // ...
   24
(lldb) n
Process 60060 stopped
* thread #1, name = 'fresh', stop reason = step over
    frame #0: 0x0000000000400a28 fresh`main at fresh.cpp:25:12
   22
   23  	    // ...
   24
-> 25  	    return 0;
   26
   27  	}
   28
(lldb) p p
error: fresh 0x000000fa: DW_TAG_member '_M_local_buf' refers to type 0x000000000000520a which extends beyond the bounds of 0x000000f1
(Person)  (name = "Alice", age = 30, height = 1.6499999999999999) ==========>>>>> we get proper name here
(lldb)

### PR DESCRIPTION
**Pull request by DhruvSrivastavaX**
Fixes issue

-  #76 

Without fix:
```
Process 15204610 stopped
thread https://github.com/DhruvSrivastavaX/lldb-for-aix/pull/1, stop reason = step over
frame #0: 0x000000010000097c fresh`main at fresh.cpp:14
11
12 // ...
13
-> 14 return 0;
15
16 }
(lldb) print p
(Person) (name = Summary Unavailable, age = 30, height = 1.6499999999999999) ======>>>> name is not printed here
(lldb) q
Quitting LLDB will kill one or more processes. Do you really want to proceed: [Y/n] y
```

With fix:
```
(lldb) n
Process 27197796 stopped
* thread #1, name = '1191468', stop reason = step over
    frame #0: 0x000000010000097c 1191468`main at 1191468.C:14
   11    
   12        // ...
   13    
-> 14        return 0;
   15    
   16    }
(lldb) p p
(Person)  (name = "Alice", age = 30, height = 1.6499999999999999)
```

Fixes both short string and long string:
```
(lldb) n
Process 26214908 stopped
* thread #1, name = '1191468_l', stop reason = step over
    frame #0: 0x00000001000009a4 1191468_l`main at 1191468_l.C:14
   11        std::string str = "Hello";
   12        std::string str_l = "Hello! This is a very very long string that goes beyond the short string limit";
   13        // ...
-> 14        std::cout << "string " << str << std::endl;
   15        std::cout << "string " << str_l << std::endl;
   16    
   17        return 0;
(lldb) p str
(std::__1::string) "Hello"
(lldb) p str_l
(std::__1::string) "Hello! This is a very very long string that goes beyond the short string limit"
```

### CODE REVIEW

File: lldb/source/Plugins/Language/CPlusPlus/LibCxx.cpp [hunk 1]
```diff
@@ -639,23 +666,23 @@ bool lldb_private::formatters::LibcxxStringSummaryProviderUTF32(
...
+    return std::make_tuple<bool, ValueObjectSP, size_t>(false, {}, {});
 
   bool success{false};
   uint64_t size = sizeobj->GetValueAsUnsigned(0, &success);
   if (!success)
-    return std::make_tuple<bool,ValueObjectSP,size_t>(false, {}, {});
+    return std::make_tuple<bool, ValueObjectSP, size_t>(false, {}, {});
 
-  return std::make_tuple(true,dataobj,size);
+  return std::make_tuple(true, dataobj, size);
```
Comment (DhruvSrivastavaX) [inline lldb/source/Plugins/Language/CPlusPlus/LibCxx.cpp:685]: clang-format changes. please ignore

**Review by HemangGadhavi — APPROVED** [review]

**Review by ravindra-shinde2 — APPROVED** [review]

**Review by ananthsureshkumar — APPROVED** [review]
