### PR TITLE
Aix 32bit support

### LINKED ISSUE #100: LLDB throws an error while printing the address of variable or pointer for 32bit binary only
For 32 bit binaries LLDB throws an error while printing the address of variable or print the pointer, 
This is because of the memory reading as we are reading 8bytes instead of 4 bytes for 32bit binaries. 
The fix is not straight forward as the entire framework is for 64bit and there is no working reference for 32it binary debugging.

we can see below kind of errors while printing.

(lldb) p &a
       
error: Couldn't materialize: couldn't allocate a temporary region for the result: memory write failed for 0x10000001f
error: errored out in DoExecute, couldn't PrepareToExecuteJITExpression

(lldb) p *data
         
error: supposed to interpret, but failed: Interpreter couldn't resolve a value during execution

And address of the argument in stack-trace/frame info not accurate 

(lldb) n
Process 34341266 stopped
* thread #1, name = 'new_32_iss', stop reason = step over
    frame #0: 0x00000000100007e4 new_32_iss`modifyUnion(**data=0x2ff228e02ff22870**, choice=1) at new_32_iss.c:65
   62    
   63    // Function to modify union data
   64    void modifyUnion(union Data *data, int choice) {
-> 65        switch (choice) {

### PR DESCRIPTION
**Pull request by HemangGadhavi**
Added support for debugging 32-bit binaries using LLDB. 
This change also refactors and extends portions of the common debugging infrastructure shared between 32-bit and 64-bit paths. As part of this update, memory reads have been optimized to fetch 1024 bytes per ptrace call, reducing the number of system calls. 
Additionally, enhancements were made to the instruction emulation component to improve code reuse and maintain a unified implementation for both 32-bit and 64-bit architectures.
 
```
# lldb iss_51_32
(lldb) target create "iss_51_32"
Current executable set to '/LLDB/hemang/testcase/iss_51_32' (powerpc).
(lldb) b main
Breakpoint 1: where = iss_51_32`main + 32 at iss_51.c:24, address = 0x10000760
(lldb) r
Process 12583214 launched: '/LLDB/hemang/testcase/iss_51_32' (powerpc)
Process 12583214 stopped
* thread #1, name = 'iss_51_32', stop reason = breakpoint 1.1
    frame #0: 0x10000760 iss_51_32`main at iss_51.c:24
   21       int choice;
   22  
   23       // Modify and print union data
-> 24       printf("Enter 1 for int, 2 for float, 3 for string: ");
   25       scanf("%d", &choice);
   26       modifyUnion(&data, choice);
   27       printUnion(&data);
(lldb) re r
General Purpose Registers:
        r0 = 0x100002d4  iss_51_32`__start + 108
        r1 = 0x2ff22850
        r2 = 0x20000f3c  TOC
        r3 = 0x00000000  
        r4 = 0x2ff22920
        r5 = 0x2ff22928
        r6 = 0x0000f032
        r7 = 0x2ff22ff8
        r8 = 0x00000000  
        r9 = 0x50fce000
       r10 = 0x00000000  
       r11 = 0x00001030
       r12 = 0x22628480
       r13 = 0xdeadbeef
       r14 = 0x00000001  
       r15 = 0x2ff22920
       r16 = 0x2ff22928
       r17 = 0xdeadbeef
       r18 = 0xdeadbeef
       r19 = 0xf0aa0b00  __mod_init
       r20 = 0xdeadbeef
       r21 = 0xdeadbeef
       r22 = 0xdeadbeef
       r23 = 0xdeadbeef
       r24 = 0xdeadbeef
       r25 = 0xdeadbeef
       r26 = 0x4c54e289
       r27 = 0x00000008  
       r28 = 0xf0325000  libpthreads.a..data + 0
       r29 = 0xd0616000
       r30 = 0x00000007  
       r31 = 0x2ff22850
        cr = 0x28628284
       msr = 0x0000d032
       xer = 0x00000000  
        lr = 0x100002d4  iss_51_32`__start + 108
       ctr = 0x00000000  
        pc = 0x10000760  iss_51_32`main + 32 at iss_51.c:24

```

### CODE REVIEW

File: lldb/include/lldb/Core/EmulateInstruction.h [hunk 1]
```diff
@@ -556,7 +556,7 @@ class EmulateInstruction : public PluginInterface {
 private:
   virtual BreakpointLocationsPredictorCreator
   GetSingleStepBreakpointLocationsPredictorCreator() {
-    if (!m_arch.IsMIPS() && !m_arch.GetTriple().isPPC64() &&
+    if (!m_arch.IsMIPS() && !m_arch.GetTriple().isPPC() &&
```
Comment (DhruvSrivastavaX) [inline lldb/include/lldb/Core/EmulateInstruction.h:559]: Please confirm that this targets both PPC and PPC64

File: lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp [hunk 2]
```diff
@@ -309,6 +318,95 @@ bool ABISysV_ppc::PrepareTrivialCall(Thread &thread, addr_t sp,
   return true;
 }
 
+bool ABISysV_ppc::PrepareTrivialCall(Thread &thread, addr_t sp,
```
Comment (DhruvSrivastavaX) [inline lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp:321]: I think we already had a variant in base patches for the toc variant? Can you please check?

File: lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp [hunk 3]
```diff
@@ -158,22 +166,31 @@ EmulateInstructionPPC64::GetOpcodeForInstruction(uint32_t opcode) {
...
+      {0xfc000003, 0x40000003, &EmulateInstructionPPC64::EmulateBC,
+       "bcla BO,BI,TARGET"},
       {0xfc0007fe, 0x4c000020, &EmulateInstructionPPC64::EmulateBCLR,
        "bclr BO,BI,BH"},
+      {0xfc0007fe, 0x4c000021, &EmulateInstructionPPC64::EmulateBCLR,
+       "bclrl BO,BI,BH"},
       {0xfc0007fe, 0x4c000420, &EmulateInstructionPPC64::EmulateBCCTR,
        "bcctr BO,BI,BH"},
+      {0xfc0007fe, 0x4c000421, &EmulateInstructionPPC64::EmulateBCCTR,
+       "bcctrl BO,BI,BH"},
```
Comment (DhruvSrivastavaX) [inline lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp:193]: Great job on these 🙂

File: lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp [hunk 4]
```diff
@@ -193,7 +210,7 @@ bool EmulateInstructionPPC64::EvaluateInstruction(uint32_t evaluate_options) {
   if (!opcode_data)
     return false;
 
-  // LLDB_LOG(log, "PPC64::EvaluateInstruction: {0}", opcode_data->name);
+  // LLDB_LOG(log, "PPC64::EvaluateInstruction: name={0}", opcode_data->name);
```
Comment (DhruvSrivastavaX) [inline lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp]: Remove

File: lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp [hunk 5]
```diff
@@ -251,6 +268,12 @@ bool EmulateInstructionPPC64::EmulateMFSPR(uint32_t opcode) {
       ReadRegisterUnsigned(eRegisterKindLLDB, GetLRRegNum(), 0, &success);
   if (!success)
     return false;
+
+  std::optional<RegisterInfo> rt_info = GetRegisterInfo(eRegisterKindLLDB, rt);
+
+  if (rt_info->byte_size == 4)
+    lr &= 0xFFFFFFFF;
```
Comment (DhruvSrivastavaX) [inline lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp:275]: Why do we need to reset the lr here? What is the use case?

File: lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp [hunk 6]
```diff
@@ -424,122 +447,314 @@ bool EmulateInstructionPPC64::EmulateADDI(uint32_t opcode) {
...
-bool EmulateInstructionPPC64::EmulateBCA(uint32_t opcode) {
-  // FIXME:32bit M
-  uint32_t M = 0;
-  uint32_t target32 = Bits32(opcode, 15, 2) << 2;
-  uint64_t target = (uint64_t)target32 + ((target32 & 0x8000) ? 0xffffffffffff0000UL : 0);
-  uint32_t BO = Bits32(opcode, 25, 21);
-  bool success;
-  uint64_t ctr_value = ReadRegisterUnsigned(eRegisterKindLLDB, GetCTRRegNum(), 0, &success);
-  if ((~BO) & (1U << 2))
+bool EmulateInstructionPPC64::EmulateBC(uint32_t opcode) {
```
Comment (DhruvSrivastavaX) [inline lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp:530]: Lets plan to integrate all your test cases related to each in our test bucket, 
to make sure they work as expected.

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp [hunk 7]
```diff
@@ -1718,32 +1722,62 @@ void NativeProcessAIX::ThreadWasCreated(NativeThreadAIX &thread) {
...
+
+      ptrace64(req, tid, (long long)&sprs, 0, 0);
+
+      gpr->cr = sprs.pt_cr;
+      gpr->msr = sprs.pt_msr;
+      gpr->xer = sprs.pt_xer;
+      gpr->lr = sprs.pt_lr;
+      gpr->ctr = sprs.pt_ctr;
+      gpr->pc = sprs.pt_iar;
+    }
```
Comment (DhruvSrivastavaX) [inline lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: Can we make this code common by declaring gpr outside or using a template?

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp [hunk 8]
```diff
@@ -1718,32 +1722,62 @@ void NativeProcessAIX::ThreadWasCreated(NativeThreadAIX &thread) {
...
+
+      sprs.pt_cr = gpr->cr;
+      sprs.pt_msr = gpr->msr;
+      sprs.pt_xer = gpr->xer;
+      sprs.pt_lr = gpr->lr;
+      sprs.pt_ctr = gpr->ctr;
+      sprs.pt_iar = gpr->pc;
+
+      ptrace64(req, tid, (long long)&sprs, 0, 0);
+    }
```
Comment (DhruvSrivastavaX) [inline lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: Can we make this code common by declaring gpr outside or using a template?

File: lldb/source/Target/RegisterContextUnwind.cpp
Comment (DhruvSrivastavaX) [inline lldb/source/Target/RegisterContextUnwind.cpp:1574]: Add a small comment since it is a hardcoded value. or move to a #define with comment

File: lldb/include/lldb/Core/EmulateInstruction.h (hunk 1 above)
Comment (HemangGadhavi) [reply lldb/include/lldb/Core/EmulateInstruction.h:559]: Yes, getting from the llvm code base, and isPPC() checks both PPC & PPC64 with LE & BE

```
  /// Tests whether the target is PowerPC (32- or 64-bit LE or BE).             
  bool isPPC() const {                                                          
    return getArch() == Triple::ppc || getArch() == Triple::ppc64 ||            
           getArch() == Triple::ppcle || getArch() == Triple::ppc64le;          
  }    
```

File: lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp (hunk 2 above)
Comment (HemangGadhavi) [reply lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp:321]: Yes, its in the `ABISysV_ppc64` but we need same for `ABISysV_ppc`, so I have add here also

File: lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp (hunk 3 above)
Comment (HemangGadhavi) [reply lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp:193]: Thanks. 🙂

File: lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp (hunk 5 above)
Comment (HemangGadhavi) [reply lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp:275]: As per the IAS document, for a 32-bit LR the value should remain 32 bits. Therefore, if byte_size == 4, it means that for the 32-bit case we are truncating the value to 32 bits, not resetting it—just ensuring that it stays within 32-bit width.

File: lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp (hunk 6 above)
Comment (HemangGadhavi) [reply lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp:530]: yes sure.

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp (hunk 7 above)
Comment (HemangGadhavi) [reply lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: I tried with template too, but there are two different cases: GPR_PPC64 and GPR_PPC, and also ptxsprs and ptsprs for 64-bit and 32-bit respectively. Because of this, the code becomes messier and less easy to understand. So for now, I’ve kept it as it is.

If you have a better idea, let me know—we can use that approach.

File: lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp [hunk 9]
```diff
@@ -309,6 +318,95 @@ bool ABISysV_ppc::PrepareTrivialCall(Thread &thread, addr_t sp,
...
+  sp -= 8;
+
+  Status error;
+  const RegisterInfo *pc_reg_info =
+      reg_ctx->GetRegisterInfo(eRegisterKindGeneric, LLDB_REGNUM_GENERIC_PC);
+  const RegisterInfo *sp_reg_info =
+      reg_ctx->GetRegisterInfo(eRegisterKindGeneric, LLDB_REGNUM_GENERIC_SP);
+  ProcessSP process_sp(thread.GetProcess());
+
+  const RegisterInfo *r2_reg_info = reg_ctx->GetRegisterInfoAtIndex(2);
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp:376]: Why are we hardcoding reg_ctx->GetRegisterInfoAtIndex(2) ? Can we define a macro which conveys what is 2 ?

File: lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp [hunk 10]
```diff
@@ -309,6 +318,95 @@ bool ABISysV_ppc::PrepareTrivialCall(Thread &thread, addr_t sp,
...
+  LLDB_LOGF(log, "Writing IP: 0x%" PRIx64, (uint64_t)func_addr);
+
+  if (!reg_ctx->WriteRegisterFromUnsigned(pc_reg_info, func_addr))
+    return false;
+
+  LLDB_LOGF(log, "Writing R2: 0x%" PRIx64, (uint64_t)toc_addr);
+  if (!reg_ctx->WriteRegisterFromUnsigned(r2_reg_info, toc_addr)) 
+    return false;
+
+  return true;
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp:407]: Are there logs added for write wrappers like reg_ctx->WriteRegisterFromUnsigned ?

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp [hunk 11]
```diff
@@ -1718,32 +1722,62 @@ void NativeProcessAIX::ThreadWasCreated(NativeThreadAIX &thread) {
...
-    gpr->xer = sprs.pt_xer;
-    gpr->lr = sprs.pt_lr;
-    gpr->ctr = sprs.pt_ctr;
-    gpr->pc = sprs.pt_iar;
+static void GetSPRs(int req, lldb::tid_t tid, void *gpr_t, size_t size) {
+    if( size == sizeof(GPR_PPC64)) {
+      GPR_PPC64 *gpr = static_cast<GPR_PPC64 *>(gpr_t);
+      struct ptxsprs sprs;
+
+      ptrace64(req, tid, (long long)&sprs, 0, 0);
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: Can we add a clear log on parameters passed to ptrace ? This will help in debugging ?

Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: Can we add a detailed log for ptrace parameters being passed, This will help in debugging ?

File: lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp [hunk 12]
```diff
@@ -309,6 +318,95 @@ bool ABISysV_ppc::PrepareTrivialCall(Thread &thread, addr_t sp,
...
+    log->PutString(s.GetString());
+  }
+
+  RegisterContext *reg_ctx = thread.GetRegisterContext().get();
+  if (!reg_ctx)
+    return false;
+
+  const RegisterInfo *reg_info = nullptr;
+
+  if (args.size() > 8) // TODO handle more than 8 arguments
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp:348]: Is the TODO still required? Can we remove ?

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp (hunk 11 above)
Comment (HemangGadhavi) [reply lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: yes its there in the main PtraceWrapper(), so need here, it will be double logs.
```
LLDB_LOG(log, "ptrace({0}, {1}, {2}, {3}, {4})={5:x}", req, pid, addr, data,
           data_size, ret);
```

File: lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp (hunk 9 above)
Comment (HemangGadhavi) [reply lldb/source/Plugins/ABI/PowerPC/ABISysV_ppc.cpp:376]: The changes in ABISysV_ppc.cpp and the PrepareTrivialCall() API are based on what the compiler implemented, and they are exactly the same for both 64-bit and 32-bit.
We still need to review the PrepareTrivialCall() API to determine whether it is actually required for both 64-bit and 32-bit, why it was introduced, and what the impact would be if we removed it. However, that is a separate task that we can take up later.
The same response applies to the other comments related to the same API.

**Review by Niranjan-bos — APPROVED** [review]

File: lldb/source/Target/RegisterContextUnwind.cpp
Comment (HemangGadhavi) [reply lldb/source/Target/RegisterContextUnwind.cpp:1574]: Done

File: lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp (hunk 4 above)
Comment (HemangGadhavi) [reply lldb/source/Plugins/Instruction/PPC64/EmulateInstructionPPC64.cpp]: Done

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp (hunk 7 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: You can try a template something like this:
```
template<typename t1, typename t2>
static void GetSPRsTemplate(int req, lldb::tid_t tid, t1 *gpr) {
    t2 sprs;
    ptrace64(req, tid, (long long)&sprs, 0, 0);
    
    gpr->cr = sprs.pt_cr;
    gpr->msr = sprs.pt_msr;
    ...
}

static void GetSPRs(int req, lldb::tid_t tid, void *gpr_t, size_t size) {
    if (size == sizeof(GPR_PPC64)) {
        GetSPRsTemplate<GPR_PPC64, ptxsprs>(req, tid, static_cast<GPR_PPC64 *>(gpr_t));
    } else {
        GetSPRsTemplate<GPR_PPC, ptsprs>(req, tid, static_cast<GPR_PPC *>(gpr_t));
    }
}
```
See if it works out, otherwise we can fix it in later PRs

Comment (HemangGadhavi) [reply lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: Thanks for the templates, its working and updated with same

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp (hunk 8 above)
Comment (HemangGadhavi) [reply lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: Done

**Review by ananthsureshkumar — APPROVED** [review]

**Review by DhruvSrivastavaX — APPROVED** [review]
