### PR TITLE
Fix for stack memory access from core file

### LINKED ISSUE #41: Stack memory region access gives error when debugging core file
Stack memory region access gives error when debugging core file

### PR DESCRIPTION
**Pull request by DhruvSrivastavaX**
This fix makes core file able to correctly access the stack memory:

```
(130) root @ unobosdev002: /home/dhruv/dio_fs/LLDB/build-lldb
# bin/lldb --core /home/dhruv/LLDB/tests/core
(lldb) target create --core "/home/dhruv/LLDB/tests/core"
Core file '/home/dhruv/LLDB/tests/core' (powerpc64) was loaded.
(lldb) list main
File: /home/dhruv/LLDB/tests/core.c
   1     int main(){
   2        char *str;
   3        int a = 10;
   4        str = "GfG";
   5        *(str+1) = 'n';
   6        return a;
   7     }
(lldb) process status
Process 18446744071562067991 stopped
* thread #1, stop reason = SIGSEGV
    frame #0: 0x0000000100000940 coretest64`main at core.c:5
   2        char *str;
   3        int a = 10;
   4        str = "GfG";
-> 5        *(str+1) = 'n';
   6        return a;
   7     }
(lldb) p a
(int) 10
(lldb) fr v a
(int) a = 10
```

### CODE REVIEW

File: lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp [hunk 1]
```diff
@@ -246,7 +276,48 @@ size_t ProcessAIXCore::ReadMemory(lldb::addr_t addr, void *buf, size_t size,
...
+    const lldb::addr_t file_start = address_range->data.GetRangeBase();
+    const lldb::addr_t file_end = address_range->data.GetRangeEnd();
+    size_t bytes_to_read = size; // Number of bytes to read from the core file
+    size_t bytes_copied = 0;   // Number of bytes actually read from the core file
+    lldb::addr_t bytes_left =
+        0; // Number of bytes available in the core file from the given address
+
+    // Don't proceed if core file doesn't contain the actual data for this
+    // address range.
+    if (file_start == file_end)
```
Comment (ravindra-shinde2) [inline lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp:304]: do we need to reset the value of file_end or file_start here?

**Review by ravindra-shinde2 — APPROVED** [review]

File: lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp (hunk 1 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp:304]: This implies that the file is "empty" or erraneous. We dont proceed then.

**Review by HemangGadhavi — APPROVED** [review]

File: lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp [hunk 2]
```diff
@@ -94,6 +94,32 @@ ProcessAIXCore::~ProcessAIXCore() {
...
 }
 
+lldb::addr_t ProcessAIXCore::AddAddressRanges(AIXCORE::AIXCore64Header header) {
+  const lldb::addr_t addr = header.StackBaseAddr;
+  FileRange file_range(header.StackOffset, header.StackSize);
+  VMRangeToFileOffset::Entry range_entry(addr, header.StackSize, file_range);
+
+  if (header.StackSize > 0) {
+    VMRangeToFileOffset::Entry *last_entry = m_core_aranges.Back();
+    if (last_entry && last_entry->GetRangeEnd() == range_entry.GetRangeBase() &&
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp]: Can we indent the code.

File: lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp [hunk 3]
```diff
@@ -180,6 +207,9 @@ Status ProcessAIXCore::DoLoadCore() {
             DataExtractor data(data_sp, lldb::eByteOrderBig, 4);
             lldb::offset_t data_offset = 0;
             m_aixcore_header.ParseCoreHeader(data, &data_offset);
+            lldb::addr_t addr = AddAddressRanges(m_aixcore_header);
+            if (addr == LLDB_INVALID_ADDRESS)
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp:212]: If the address is invalid, Should we continue?

File: lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp [hunk 4]
```diff
@@ -246,7 +276,48 @@ size_t ProcessAIXCore::ReadMemory(lldb::addr_t addr, void *buf, size_t size,
...
+    }
+
+    // Convert the address into core file offset
+    const lldb::addr_t offset = addr - address_range->GetRangeBase();
+    const lldb::addr_t file_start = address_range->data.GetRangeBase();
+    const lldb::addr_t file_end = address_range->data.GetRangeEnd();
+    size_t bytes_to_read = size; // Number of bytes to read from the core file
+    size_t bytes_copied = 0;   // Number of bytes actually read from the core file
+    lldb::addr_t bytes_left =
+        0; // Number of bytes available in the core file from the given address
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp]: Indentation...

File: lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp [hunk 5]
```diff
@@ -246,7 +276,48 @@ size_t ProcessAIXCore::ReadMemory(lldb::addr_t addr, void *buf, size_t size,
...
+    if (file_end > file_start + offset)
+        bytes_left = file_end - (file_start + offset);
+
+    if (bytes_to_read > bytes_left)
+        bytes_to_read = bytes_left;
+
+  // If there is data available on the core file read it
+  if (bytes_to_read)
+    bytes_copied =
+        core_objfile->CopyData(offset + file_start, bytes_to_read, buf);
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp:318]: Can the CopyData fail? Should we capture the errno in failure case ?  Or the caller of DoReadMemory should validate the copy was successful!

File: lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp (hunk 2 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp]: Done

File: lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp (hunk 3 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp:212]: We can, only the stack address space will be unaccessible. 
Other information will still be available.

File: lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp (hunk 4 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp]: Done

File: lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp (hunk 5 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/aix-core/ProcessAIXCore.cpp:318]: If CopyData fails, it will return 0, making bytes_copied 0 which will be traversed above and handled by the topmost caller.

**Review by ananthsureshkumar — APPROVED** [review]
