### PR TITLE
Global variables are not accessed correctly

### LINKED ISSUE #35: Global variable's value not updated during a debug session
```
# bin/lldb ../tests/global
(lldb) target create "../tests/global"
Current executable set to '/home/dhruv/dio_fs/LLDB/tests/global' (powerpc64).
(lldb) b main
Breakpoint 2: where = global`main + 12 at global.c:4, address = 0x000000010000092c
(lldb) r
Process 33423848 launched: '/home/dhruv/dio_fs/LLDB/tests/global' (powerpc64)
Process 33423848 stopped
* thread #1, stop reason = breakpoint 2.1
    frame #0: 0x000000010000092c global`main at global.c:4
   1    int g = 5;
   2    int main()
   3    {
-> 4            int x = 10;
   5            int y = x - (--g);
   6            return y;
   7    }
(lldb) p g
(int) 5
(lldb) n
Process 33423848 stopped
* thread #1, stop reason = step over
    frame #0: 0x0000000100000930 global`main at global.c:5
   2    int main()
   3    {
   4            int x = 10;
-> 5            int y = x - (--g);
   6            return y;
   7    }
(lldb) p g
(int) 5
(lldb) fr v g
(int) g = 5
(lldb) n
Process 33423848 stopped
* thread #1, stop reason = step over
    frame #0: 0x0000000100000950 global`main at global.c:6
   3    {
   4            int x = 10;
   5            int y = x - (--g);
-> 6            return y;
   7    }
(lldb) p g
(int) 5
(lldb) fr v g
(int) g = 5
(lldb) list
(lldb) list main
File: /home/dhruv/dio_fs/LLDB/tests/global.c
   1    int g = 5;
   2    int main()
   3    {
   4            int x = 10;
   5            int y = x - (--g);
   6            return y;
   7    }
(lldb) q
```

the value of g remains same.

### LINKED ISSUE #42: In lldb, print does not works properly sometimes
C file:-
---------
#include<stdio.h>
void f(int x);
static int x;

int main()
{
    x = 2;
    f(3);
    f(4);
    return(0);
}

static int y = 0;

void f(x)
int x;
{
    static int z = 0;
    z += x;
}

How to compile:-
-----------------

/opt/IBM/openxlC/17.1.2/bin/ibm-clang_r -o static static.c -m64 -g

Log:-
------

# lldb static
(lldb) target create "static"
Current executable set to '/home/LLDB/package/bin/static' (powerpc64).
(lldb) b main
Breakpoint 1: where = static`main + 28 at static.c:7, address = 0x000000010000093c
(lldb) r
Process 7537356 launched: '/home/LLDB/package/bin/static' (powerpc64)
Process 7537356 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x000000010000093c static`main at static.c:7
   4
   5   	int main()
   6   	{
-> 7   	    x = 2;
   8   	    f(3);
   9   	    f(4);
   10  	    return(0);
(lldb) n
Process 7537356 stopped
* thread #1, stop reason = step over
    frame #0: 0x000000010000094c static`main at static.c:8
   5   	int main()
   6   	{
   7   	    x = 2;
-> 8   	    f(3);
   9   	    f(4);
   10  	    return(0);
   11  	}
(lldb) print x
(int) 32964615 ================>>>>>>>>>>>>> expecting o/p here as 2
(lldb) n
Process 7537356 stopped
* thread #1, stop reason = step over
    frame #0: 0x0000000100000958 static`main at static.c:9
   6   	{
   7   	    x = 2;
   8   	    f(3);
-> 9   	    f(4);
   10  	    return(0);
   11  	}
   12
(lldb) p x
(int) 32964615 ================>>>>>>>>>>>>> expecting o/p here as 2
(lldb) f
frame #0: 0x0000000100000958 static`main at static.c:9
   6   	{
   7   	    x = 2;
   8   	    f(3);
-> 9   	    f(4);
   10  	    return(0);
   11  	}
   12
(lldb) s

Dbx log:-
---------
# dbx static
Type 'help' for help.
reading symbolic information ...
(dbx) st in main
[1] stop in main
(dbx) r
[1] stopped in main at line 7 ($t1)
    7       x = 2;
(dbx) n
stopped in main at line 8 ($t1)
    8       f(3);
(dbx) p x
2                                                     ====================>>>>>>>>>>> here dbx prints properly as 2
(dbx)

Tested on gdb also, here also it prints as 2 properly
-----------------------------------------------------
# gdb sta
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-20.el8
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "ppc64le-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from sta...done.
(gdb) br main
Breakpoint 1 at 0x100005e8: file sta.c, line 7.
(gdb) r
Starting program: /home/sta

Breakpoint 1, main () at sta.c:7
7	    x = 2;
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-251.el8_10.5.ppc64le
(gdb) n
8	    f(3);
(gdb) print x
$1 = 2                                                    ====================>>>>>>>>>>> here gdb prints properly as 2
(gdb) n
9	    f(4);
(gdb) p x
$2 = 2                                                    ====================>>>>>>>>>>> here gdb prints properly as 2
(gdb) n
10	    return(0);
(gdb) q
A debugging session is active.

### PR DESCRIPTION
**Pull request by ravindra-shinde2**
Fixed the issue with respect to global variables are not accessd, as the address for the data and bss sections is corrupted.

### CODE REVIEW

File: lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp [hunk 1]
```diff
@@ -335,15 +335,28 @@ bool ObjectFileXCOFF::SetLoadAddress(Target &target, lldb::addr_t value,
...
+              ++num_loaded_sections;
+	  }
+	  else if (strcmp(section_sp->GetName().AsCString(), ".data") == 0 ||
+	    strcmp(section_sp->GetName().AsCString(), ".bss") == 0)
+	  {
+	    if (target.GetSectionLoadListPublic().SetSectionLoadAddress(
+		section_sp, section_sp->GetFileAddress()))
+	      ++num_loaded_sections;
+	  }
+	  else
```
Comment (HemangGadhavi) [inline lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp]: Just see if we can club first if() and last else() case

File: lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp [hunk 2]
```diff
@@ -335,15 +335,28 @@ bool ObjectFileXCOFF::SetLoadAddress(Target &target, lldb::addr_t value,
...
+	  {
+	    if (target.GetSectionLoadListPublic().SetSectionLoadAddress(
+	      section_sp, (use_offset ?
+	      (section_sp->GetFileOffset() + value) : (section_sp->GetFileAddress() + value))))
```
Comment (HemangGadhavi) [inline lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp]: we were seeing issue for the other section addresses not updated (.dwranges and all)
is that addressed?

**Comment by ananthsureshkumar** [comment]
Pls update the test results clearly here..

File: lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp [hunk 3]
```diff
@@ -335,15 +335,28 @@ bool ObjectFileXCOFF::SetLoadAddress(Target &target, lldb::addr_t value,
...
-              strcmp(section_sp->GetName().AsCString(), ".bss") == 0)
+          if (strcmp(section_sp->GetName().AsCString(), ".text") == 0)
+	  {
             use_offset = true;
-
-          if (target.GetSectionLoadListPublic().SetSectionLoadAddress(
-                  section_sp, (use_offset ?
-                  (section_sp->GetFileOffset() + value) : (section_sp->GetFileAddress() + value))))
-            ++num_loaded_sections;
+	    if (target.GetSectionLoadListPublic().SetSectionLoadAddress(
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp]: Pls indent the code.

File: lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp [hunk 4]
```diff
@@ -335,15 +335,28 @@ bool ObjectFileXCOFF::SetLoadAddress(Target &target, lldb::addr_t value,
...
+	  }
+	  else if (strcmp(section_sp->GetName().AsCString(), ".data") == 0 ||
+	    strcmp(section_sp->GetName().AsCString(), ".bss") == 0)
+	  {
+	    if (target.GetSectionLoadListPublic().SetSectionLoadAddress(
+		section_sp, section_sp->GetFileAddress()))
+	      ++num_loaded_sections;
+	  }
+	  else
+	  {
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp]: Add a general comment on what all sections can fall under the else condition.

File: lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp (hunk 1 above)
Comment (ravindra-shinde2) [reply lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp]: Agreed, I have made the change.

File: lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp (hunk 2 above)
Comment (ravindra-shinde2) [reply lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp]: It will be updated, but we are not sure if those are correct. After running the (run) command, these adresess are getting updated.

**Loaded the binary (target create binary)** 
(lldb) image dump sections
Dumping sections for 1 modules.
Sections for '/home/ravi/lldb_def/1188732_print1' (powerpc64):
  SectID             Type                   File Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x0000000100000438-0x0000000100000a3b)  r-x  0x00000438 0x00000603 0x00000020 1188732_print1..text
  0x0000000000000002 data                   [0x0000000110000a3b-0x0000000110000da0)  rw-  0x00000a3b 0x00000365 0x00000040 1188732_print1..data
  0x0000000000000003 zero-fill              [0x0000000110000da0-0x0000000110000dc8)  rw-  0x00000000 0x00000028 0x00000080 1188732_print1..bss
  0x0000000000000004 regular                [0x0000000000000000-0x000000000000052a)  r--  0x00000da0 0x0000052a 0x00001000 1188732_print1..loader
  0x0000000000000005 dwarf-line             [**0x0000000000000000-0x0000000000000059**)  r--  0x000012ca 0x00000059 0x00020010 1188732_print1..dwline
  0x0000000000000006 dwarf-info             [**0x0000000000000000-0x000000000000019e**)  r--  0x00001324 0x0000019e 0x00010010 1188732_print1..dwinfo
  0x0000000000000007 dwarf-abbrev           [**0x0000000000000000-0x000000000000008f**)  r--  0x000014c2 0x0000008f 0x00060010 1188732_print1..dwabrev

**After running the executable:**
(lldb) image dump sections
Dumping sections for 7 modules.
Sections for '/home/ravi/lldb_def/1188732_print1' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x0000000100000438-0x0000000100000a3b)  r-x  0x00000438 0x00000603 0x00000020 1188732_print1..text
  0x0000000000000002 data                   [0x0000000110000a3b-0x0000000110000da0)  rw-  0x00000a3b 0x00000365 0x00000040 1188732_print1..data
  0x0000000000000003 zero-fill              [0x0000000110000da0-0x0000000110000dc8)  rw-  0x00000000 0x00000028 0x00000080 1188732_print1..bss
  0x0000000000000004 regular                [**0x0000000100000000-0x000000010000052a**)  r--  0x00000da0 0x0000052a 0x00001000 1188732_print1..loader
  0x0000000000000005 dwarf-line             [**0x0000000100000000-0x0000000100000059**)  r--  0x000012ca 0x00000059 0x00020010 1188732_print1..dwline
  0x0000000000000006 dwarf-info             [**0x0000000100000000-0x000000010000019e**)  r--  0x00001324 0x0000019e 0x00010010 1188732_print1..dwinfo
  0x0000000000000007 dwarf-abbrev           [**0x0000000100000000-0x000000010000008f**)  r--  0x000014c2 0x0000008f 0x00060010 1188732_print1..dwabrev

Comment (HemangGadhavi) [reply lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp]: You can confirm with llvm-dwarfdump

below is just an example of llvm-dwarfdump contain .debug_ranges

.debug_ranges contents:                                                                                                                              
00000000 **0000000010000b2c** 0000000010000dec                                      
00000000 0000000010000dec 0000000010000e3c                                      
00000000 0000000010000e3c 0000000010000e8c

**0000000010000b2c** this could be the starting address of the .dwranges section. Not sure but just check once if it helps.

**Comment by ravindra-shinde2** [comment]
**Test Case:**
#include<stdio.h>
void f(int x);
static int x;

int main()
{
    x = 2;
    f(3);
    f(4);
    return(0);
}

static int y = 0;

void f(int x)
{
    static int z = 0;
    z += x;
}

**## Output Analysis ##**
**Without Fix -** 

(lldb) b main
Breakpoint 1: where = 1188732_print1`main + 28 at 1188732_print1.c:7, address = 0x000000010000093c
(lldb) r
Process 40960326 launched: '/home/ravi/lldb_def/1188732_print1' (powerpc64)
Process 40960326 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x000000010000093c 1188732_print1`main at 1188732_print1.c:7
   4     
   5     int main()
   6     {
-> 7         x = 2;
   8         f(3);
   9         f(4);
   10        return(0);
(lldb) p x
(int) 32964615
(lldb) p &x
(int *) 0x0000000100000000
(lldb) n
Process 40960326 stopped
* thread #1, stop reason = step over
    frame #0: 0x000000010000094c 1188732_print1`main at 1188732_print1.c:8
   5     int main()
   6     {
   7         x = 2;
-> 8         f(3);
   9         f(4);
   10        return(0);
   11    }
(lldb) n
Process 40960326 stopped
* thread #1, stop reason = step over
    frame #0: 0x0000000100000958 1188732_print1`main at 1188732_print1.c:9
   6     {
   7         x = 2;
   8         f(3);
-> 9         f(4);
   10        return(0);
   11    }
   12    
(lldb) p x
(int) 32964615
(lldb) p &x
(int *) 0x0000000100000000
(lldb) 


**With Fix -** 
(lldb) b main
Breakpoint 1: where = 1188732_print1`main + 28 at 1188732_print1.c:7, address = 0x000000010000093c
(lldb) r
Process 22348210 launched: '/home/ravi/lldb_def/1188732_print1' (powerpc64)
Process 22348210 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x000000010000093c 1188732_print1`main at 1188732_print1.c:7
   4     
   5     int main()
   6     {
-> 7         x = 2;
   8         f(3);
   9         f(4);
   10        return(0);
(lldb) p x
(int) 0
(lldb) p &x
(int *) 0x0000000110000d18
(lldb) n
Process 22348210 stopped
* thread #1, stop reason = step over
    frame #0: 0x000000010000094c 1188732_print1`main at 1188732_print1.c:8
   5     int main()
   6     {
   7         x = 2;
-> 8         f(3);
   9         f(4);
   10        return(0);
   11    }
(lldb) n
Process 22348210 stopped
* thread #1, stop reason = step over
    frame #0: 0x0000000100000958 1188732_print1`main at 1188732_print1.c:9
   6     {
   7         x = 2;
   8         f(3);
-> 9         f(4);
   10        return(0);
   11    }
   12    
(lldb) p x
(int) 2
(lldb) p &x
(int *) 0x0000000110000d18
(lldb)

**Comment by DhruvSrivastavaX** [comment]
Looks better handled with the optimised change. 
Just check on the other section ranges if they are fetched correctly, to be sure

**Comment by ravindra-shinde2** [comment]
**Without Fix:**

(lldb) image dump sections
Dumping sections for 1 modules.
Sections for '/home/ravi/lldb_def/1188732_print1' (powerpc64):
  SectID             Type                   File Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x0000000100000438-0x00000001000009c7)  r-x  0x00000438 0x0000058f 0x00000020 1188732_print1..text
  0x0000000000000002 data                   [**0x00000001100009c7-0x0000000110000d18**)  rw-  0x000009c7 0x00000351 0x00000040 1188732_print1..data
  0x0000000000000003 zero-fill              [**0x0000000110000d18-0x0000000110000d40**)  rw-  0x00000000 0x00000028 0x00000080 1188732_print1..bss
  0x0000000000000004 regular                [**0x0000000000000000-0x00000000000004e9**)  r--  0x00000d18 0x000004e9 0x00001000 1188732_print1..loader
  0x0000000000000005 dwarf-line             [**0x0000000000000000-0x00000000000000cf**)  r--  0x00001202 0x000000cf 0x00020010 1188732_print1..dwline
  0x0000000000000006 dwarf-info             [**0x0000000000000000-0x0000000000000116**)  r--  0x000012d2 0x00000116 0x00010010 1188732_print1..dwinfo
  0x0000000000000007 dwarf-abbrev           [**0x0000000000000000-0x0000000000000067**)  r--  0x000013e8 0x00000067 0x00060010 1188732_print1..dwabrev
(lldb) b main
Breakpoint 1: where = 1188732_print1`main + 28 at 1188732_print1.c:7, address = 0x000000010000093c
(lldb) r
Process 24772920 launched: '/home/ravi/lldb_def/1188732_print1' (powerpc64)
Process 24772920 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x000000010000093c 1188732_print1`main at 1188732_print1.c:7
   4   
   5    int main()
   6    {
-> 7        x = 2;
   8        f(3);
   9        f(4);
   10       return(0);
(lldb) image dump sections
Dumping sections for 7 modules.
Sections for '/home/ravi/lldb_def/1188732_print1' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x0000000100000438-0x00000001000009c7)  r-x  0x00000438 0x0000058f 0x00000020 1188732_print1..text
  0x0000000000000002 data                   [**0x00000001000009c7-0x0000000100000d18**)  rw-  0x000009c7 0x00000351 0x00000040 1188732_print1..data
  0x0000000000000003 zero-fill              [**0x0000000100000000-0x0000000100000028**)  rw-  0x00000000 0x00000028 0x00000080 1188732_print1..bss
  0x0000000000000004 regular                [**0x0000000100000000-0x00000001000004e9**)  r--  0x00000d18 0x000004e9 0x00001000 1188732_print1..loader
  0x0000000000000005 dwarf-line             [**0x0000000100000000-0x00000001000000cf**)  r--  0x00001202 0x000000cf 0x00020010 1188732_print1..dwline
  0x0000000000000006 dwarf-info             [**0x0000000100000000-0x0000000100000116**)  r--  0x000012d2 0x00000116 0x00010010 1188732_print1..dwinfo
  0x0000000000000007 dwarf-abbrev           [**0x0000000100000000-0x0000000100000067**)  r--  0x000013e8 0x00000067 0x00060010 1188732_print1..dwabrev
Sections for '/usr/ccs/bin/usla64' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x09fffffff0001000-0x09fffffff00109b0)  r-x  0x00001000 0x0000f9b0 0x00000020 usla64..text
  0x0000000000000002 data                                                            rw-  0x00000000 0x00000000 0x00000040 usla64..data
  0x0000000000000003 zero-fill                                                       rw-  0x00000000 0x00000000 0x00000080 usla64..bss
  0x0000000000000004 regular                [0x0000000000000000-0x000000000000083e)* r--  0x00011000 0x0000083e 0x00001000 usla64..loader
Sections for '/usr/lib/libpthreads.a(_shr_xpg5_64.o)' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x09000000006b2200-0x09000000006dff0f)  r-x  0x00000200 0x0002dd0f 0x00000020 libpthreads.a..text
  0x0000000000000002 data                   [0x09001000a01f0000-0x09001000a01f4ca8)  rw-  0x0002e000 0x00004ca8 0x00000040 libpthreads.a..data
  0x0000000000000003 zero-fill              [0x0000000000004ca8-0x0000000000004ce4)* rw-  0x00000000 0x0000003c 0x00000080 libpthreads.a..bss
  0x0000000000000004 regular                [0x0000000000000000-0x0000000000009dd1)* r--  0x00032ca8 0x00009dd1 0x00001000 libpthreads.a..loader
Sections for '/usr/lib/libcrypt.a(shr_64.o)' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x09000000006b1420-0x09000000006b17a8)  r-x  0x00000200 0x00000388 0x00000020 libcrypt.a..text
  0x0000000000000002 data                   [0x09001000a01447a8-0x09001000a0144950)  rw-  0x00000588 0x000001a8 0x00000040 libcrypt.a..data
  0x0000000000000003 zero-fill                                                       rw-  0x00000000 0x00000000 0x00000080 libcrypt.a..bss
  0x0000000000000004 regular                [0x0000000000000000-0x000000000000034e)* r--  0x00000730 0x0000034e 0x00001000 libcrypt.a..loader
Sections for '/usr/lib/libc.a(_shr_64.o)' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x090000000022c900-0x09000000005de610)  r-x  0x00000280 0x003b1d10 0x00000020 libc.a..text
  0x0000000000000002 data                   [0x09001000a00bb610-0x09001000a0133930)  rw-  0x003b1f90 0x00078320 0x00000040 libc.a..data
  0x0000000000000003 zero-fill              [0x0000000000078320-0x0000000000088008)* rw-  0x00000000 0x0000fce8 0x00000080 libc.a..bss
  0x0000000000000004 regular                [0x0000000000000000-0x000000000005a0d5)* r--  0x0042a2b0 0x0005a0d5 0x00001000 libc.a..loader
  0x0000000000000005 regular                [0x0000000000000000-0x0000000000000028)* r--  0x00484386 0x00000028 0x00000100 libc.a..except
Sections for '/usr/lib/libpthreads.a(shr_xpg5_64.o)' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x09000000000b71f8-0x09000000000b7343)  r-x  0x000001f8 0x0000014b 0x00000020 libpthreads.a..text
  0x0000000000000002 data                   [0x09001000a0164348-0x09001000a0166bb0)  rw-  0x00000348 0x00002868 0x00000040 libpthreads.a..data
  0x0000000000000003 zero-fill              [0x0000000000002868-0x000000000008b09c)* rw-  0x00000000 0x00088834 0x00000080 libpthreads.a..bss
  0x0000000000000004 regular                [0x0000000000000000-0x00000000000092c5)* r--  0x00002bb0 0x000092c5 0x00001000 libpthreads.a..loader
Sections for '/usr/lib/libc.a(shr_64.o)' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x09000000000001f8-0x090000000000031a)  r-x  0x000001f8 0x00000122 0x00000020 libc.a..text
  0x0000000000000002 data                   [0x09001000a0000320-0x09001000a004a300)  rw-  0x00000320 0x00049fe0 0x00000040 libc.a..data
  0x0000000000000003 zero-fill              [0x0000000000049fe0-0x00000000000ba09c)* rw-  0x00000000 0x000700bc 0x00000080 libc.a..bss
  0x0000000000000004 regular                [0x0000000000000000-0x000000000006bf77)* r--  0x0004a300 0x0006bf77 0x00001000 libc.a..loader


**With Fix:**
(lldb) target create ../ravi/lldb_def/1188732_print1
Current executable set to '/home/ravi/lldb_def/1188732_print1' (powerpc64).
(lldb) image dump sections
Dumping sections for 1 modules.
Sections for '/home/ravi/lldb_def/1188732_print1' (powerpc64):
  SectID             Type                   File Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x0000000100000438-0x00000001000009c7)  r-x  0x00000438 0x0000058f 0x00000020 1188732_print1..text
  0x0000000000000002 data                   [**0x00000001100009c7-0x0000000110000d18**)  rw-  0x000009c7 0x00000351 0x00000040 1188732_print1..data
  0x0000000000000003 zero-fill              [**0x0000000110000d18-0x0000000110000d40**)  rw-  0x00000000 0x00000028 0x00000080 1188732_print1..bss
  0x0000000000000004 regular                [**0x0000000000000000-0x00000000000004e9**)  r--  0x00000d18 0x000004e9 0x00001000 1188732_print1..loader
  0x0000000000000005 dwarf-line             [**0x0000000000000000-0x00000000000000cf**)  r--  0x00001202 0x000000cf 0x00020010 1188732_print1..dwline
  0x0000000000000006 dwarf-info             [**0x0000000000000000-0x0000000000000116**)  r--  0x000012d2 0x00000116 0x00010010 1188732_print1..dwinfo
  0x0000000000000007 dwarf-abbrev           [**0x0000000000000000-0x0000000000000067**)  r--  0x000013e8 0x00000067 0x00060010 1188732_print1..dwabrev
(lldb) b main
Breakpoint 1: where = 1188732_print1`main + 28 at 1188732_print1.c:7, address = 0x000000010000093c
(lldb) r
Process 22282660 launched: '/home/ravi/lldb_def/1188732_print1' (powerpc64)
Process 22282660 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x000000010000093c 1188732_print1`main at 1188732_print1.c:7
   4   
   5    int main()
   6    {
-> 7        x = 2;
   8        f(3);
   9        f(4);
   10       return(0);
(lldb) image dump sections
Dumping sections for 7 modules.
Sections for '/home/ravi/lldb_def/1188732_print1' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x0000000100000438-0x00000001000009c7)  r-x  0x00000438 0x0000058f 0x00000020 1188732_print1..text
  0x0000000000000002 data                   [**0x00000001100009c7-0x0000000110000d18**)  rw-  0x000009c7 0x00000351 0x00000040 1188732_print1..data
  0x0000000000000003 zero-fill              [**0x0000000110000d18-0x0000000110000d40**)  rw-  0x00000000 0x00000028 0x00000080 1188732_print1..bss
  0x0000000000000004 regular                [**0x0000000000000000-0x00000000000004e9**)  r--  0x00000d18 0x000004e9 0x00001000 1188732_print1..loader
  0x0000000000000005 dwarf-line             [**0x0000000000000000-0x00000000000000cf**)  r--  0x00001202 0x000000cf 0x00020010 1188732_print1..dwline
  0x0000000000000006 dwarf-info             [**0x0000000000000000-0x0000000000000116**)  r--  0x000012d2 0x00000116 0x00010010 1188732_print1..dwinfo
  0x0000000000000007 dwarf-abbrev           [**0x0000000000000000-0x0000000000000067**)  r--  0x000013e8 0x00000067 0x00060010 1188732_print1..dwabrev
Sections for '/usr/ccs/bin/usla64' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x09fffffff0001000-0x09fffffff00109b0)  r-x  0x00001000 0x0000f9b0 0x00000020 usla64..text
  0x0000000000000002 data                                                            rw-  0x00000000 0x00000000 0x00000040 usla64..data
  0x0000000000000003 zero-fill                                                       rw-  0x00000000 0x00000000 0x00000080 usla64..bss
  0x0000000000000004 regular                [0x0000000000000000-0x000000000000083e)* r--  0x00011000 0x0000083e 0x00001000 usla64..loader
Sections for '/usr/lib/libpthreads.a(_shr_xpg5_64.o)' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x09000000006b2200-0x09000000006dff0f)  r-x  0x00000200 0x0002dd0f 0x00000020 libpthreads.a..text
  0x0000000000000002 data                   [0x09001000a01f0000-0x09001000a01f4ca8)  rw-  0x0002e000 0x00004ca8 0x00000040 libpthreads.a..data
  0x0000000000000003 zero-fill              [0x0000000000004ca8-0x0000000000004ce4)* rw-  0x00000000 0x0000003c 0x00000080 libpthreads.a..bss
  0x0000000000000004 regular                [0x0000000000000000-0x0000000000009dd1)* r--  0x00032ca8 0x00009dd1 0x00001000 libpthreads.a..loader
Sections for '/usr/lib/libcrypt.a(shr_64.o)' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x09000000006b1420-0x09000000006b17a8)  r-x  0x00000200 0x00000388 0x00000020 libcrypt.a..text
  0x0000000000000002 data                   [0x09001000a01447a8-0x09001000a0144950)  rw-  0x00000588 0x000001a8 0x00000040 libcrypt.a..data
  0x0000000000000003 zero-fill                                                       rw-  0x00000000 0x00000000 0x00000080 libcrypt.a..bss
  0x0000000000000004 regular                [0x0000000000000000-0x000000000000034e)* r--  0x00000730 0x0000034e 0x00001000 libcrypt.a..loader
Sections for '/usr/lib/libc.a(_shr_64.o)' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x090000000022c900-0x09000000005de610)  r-x  0x00000280 0x003b1d10 0x00000020 libc.a..text
  0x0000000000000002 data                   [0x09001000a00bb610-0x09001000a0133930)  rw-  0x003b1f90 0x00078320 0x00000040 libc.a..data
  0x0000000000000003 zero-fill              [0x0000000000078320-0x0000000000088008)* rw-  0x00000000 0x0000fce8 0x00000080 libc.a..bss
  0x0000000000000004 regular                [0x0000000000000000-0x000000000005a0d5)* r--  0x0042a2b0 0x0005a0d5 0x00001000 libc.a..loader
  0x0000000000000005 regular                [0x0000000000000000-0x0000000000000028)* r--  0x00484386 0x00000028 0x00000100 libc.a..except
Sections for '/usr/lib/libpthreads.a(shr_xpg5_64.o)' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x09000000000b71f8-0x09000000000b7343)  r-x  0x000001f8 0x0000014b 0x00000020 libpthreads.a..text
  0x0000000000000002 data                   [0x09001000a0164348-0x09001000a0166bb0)  rw-  0x00000348 0x00002868 0x00000040 libpthreads.a..data
  0x0000000000000003 zero-fill              [0x0000000000002868-0x000000000008b09c)* rw-  0x00000000 0x00088834 0x00000080 libpthreads.a..bss
  0x0000000000000004 regular                [0x0000000000000000-0x00000000000092c5)* r--  0x00002bb0 0x000092c5 0x00001000 libpthreads.a..loader
Sections for '/usr/lib/libc.a(shr_64.o)' (powerpc64):
  SectID             Type                   Load Address                             Perm File Off.  File Size  Flags      Section Name
  ------------------ ---------------------- ---------------------------------------  ---- ---------- ---------- ---------- ----------------------------
  0x0000000000000001 code                   [0x09000000000001f8-0x090000000000031a)  r-x  0x000001f8 0x00000122 0x00000020 libc.a..text
  0x0000000000000002 data                   [0x09001000a0000320-0x09001000a004a300)  rw-  0x00000320 0x00049fe0 0x00000040 libc.a..data
  0x0000000000000003 zero-fill              [0x0000000000049fe0-0x00000000000ba09c)* rw-  0x00000000 0x000700bc 0x00000080 libc.a..bss
  0x0000000000000004 regular                [0x0000000000000000-0x000000000006bf77)* r--  0x0004a300 0x0006bf77 0x00001000 libc.a..loader

**Review by HemangGadhavi — APPROVED** [review]

File: lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp [hunk 5]
```diff
@@ -333,16 +334,19 @@ bool ObjectFileXCOFF::SetLoadAddress(Target &target, lldb::addr_t value,
...
 
+        if (section_sp && !section_sp->IsThreadSpecific()) {
+          addr_t load_addr = 0;
+          if (!value_is_offset)
+            load_addr = section_sp->GetFileAddress();
+          else {
+            if (strcmp(section_sp->GetName().AsCString(), ".text") == 0)
+              load_addr = section_sp->GetFileOffset() + value;
+            else /* Other sections: data, bss, loader, dwline, dwinfo, dwabrev */
+              load_addr = section_sp->GetFileAddress() + value;
```
Comment (DhruvSrivastavaX) [inline lldb/source/Plugins/ObjectFile/XCOFF/ObjectFileXCOFF.cpp:346]: why are we adding value for bss and data? that will again change the address

**Review by DhruvSrivastavaX — APPROVED** [review]
So, as @ravindra-shinde2 , @HemangGadhavi and Me have discussed, we will get back on this for a more optimized implementation to check the values passed by `value` and `value_is_offset`. 
For now, this is fixing the issue as well as the `image dump sections` data

**Review by ananthsureshkumar — APPROVED** [review]
Approving now. Pls open a GITHUB issue to track the other scenarios observed as a part of testing.
