### PR TITLE
Fix for delay while quitting debugging session

### LINKED ISSUE #47: LLDB takes time to quit debugging session
Once we have a running debuggee, LLDB takes ~15 seconds to quit. 

```
(0) root @ unobosdev002: /home/dhruv/dio_fs/LLDB/build-lldb
# bin/lldb ../tests/1
(lldb) target create "../tests/1"
Current executable set to '/home/dhruv/dio_fs/LLDB/tests/1' (powerpc64).
(lldb) b main
Breakpoint 1: where = 1`main + 8 at 1.c:3, address = 0x00000001000008a0
(lldb) r
Process 30409082 launched: '/home/dhruv/dio_fs/LLDB/tests/1' (powerpc64)
Process 30409082 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x00000001000008a0 1`main at 1.c:3
   1     int main()
   2     {
-> 3         int x = 10;
   4         x++;
   5         return x;
   6     }
(lldb) q
Quitting LLDB will kill one or more processes. Do you really want to proceed: [Y/n] y
```

### PR DESCRIPTION
**Pull request by DhruvSrivastavaX**
Once we have a running debuggee, LLDB takes a couple of seconds to quit.
This fix makes the quit, immediate.

```
(0) root @ unobosdev002: /home/dhruv/dio_fs/LLDB/build-lldb
# bin/lldb ../tests/1
(lldb) target create "../tests/1"
Current executable set to '/home/dhruv/dio_fs/LLDB/tests/1' (powerpc64).
(lldb) b main
Breakpoint 1: where = 1`main + 8 at 1.c:3, address = 0x00000001000008a0
(lldb) r
Process 30409082 launched: '/home/dhruv/dio_fs/LLDB/tests/1' (powerpc64)
Process 30409082 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x00000001000008a0 1`main at 1.c:3
   1     int main()
   2     {
-> 3         int x = 10;
   4         x++;
   5         return x;
   6     }
(lldb) q
Quitting LLDB will kill one or more processes. Do you really want to proceed: [Y/n] y
```

### CODE REVIEW

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp [hunk 1]
```diff
@@ -953,10 +953,7 @@ Status NativeProcessAIX::Kill() {
     break;
   }
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: Some comments on why we changed to ptrace will be helpful.

**Review by ravindra-shinde2 — APPROVED** [review]

**Review by HemangGadhavi — APPROVED** [review]

**Review by Niranjan-bos — APPROVED** [review]

**Review by ananthsureshkumar — APPROVED** [review]
