### PR TITLE
First time attach resolution

### LINKED ISSUE #9: Attach to AIX Process in LLDB
This issue is related to supporting the debugging of an attached process using LLDB on AIX.

Parent issue for all implementations going on for Attach in AIX 64-bit Process.

- [x] 1. Basic debugging support for Attached Process [Enhancement]
- [x] 2. Coredump issue when Libarary calls are involved in Attach Process debugging [Enhancement]
- [x] 3. LLDB is unable to recognise a process by PID in the first Attach trial [Bug]

Other bugs encountered in the process will be added as sub issues here.

### LINKED ISSUE #12: Issue with attaching in first try
When trying to attach for the first time to an AIX process, LLDB fails to find it

### PR DESCRIPTION
**Pull request by HemangGadhavi**
Sometime LLDB is throwing error "No such a process" while attaching to the fresh process.

The issue is with ptrace64() kernel system call, as in certain cases ptrace send the SIGCHLD signal to the debugger, Which will wake up the debugger and attach is failing. 

To overcome this issue, we have to block the SIGCHLD signal before attach work and again we have unblock the signal after attaching.

Before FIX:
-------------
(0) root @ unobosdev001: /LLDB/hemang/build_1
$ bin/lldb
(lldb) attach -p 20120044
error: attach failed: No such process

After FIX:
-------------
(0) root @ unobosdev001: /LLDB/hemang/build_1
$ bin/lldb
(lldb) attach -p 25559428
Process 25559428 stopped
* thread #1, stop reason = signal SIGSTOP
    frame #0: 0x00000001000008a8 t1`main at t1.c:4
   1     int main()
   2     {
   3             int a = 0;
-> 4             while(1);
   5             return a;
   6     }
Executable binary set to "../testcase/t1".
Architecture set to: powerpc64-ibm-aix.

### CODE REVIEW

**Review by DhruvSrivastavaX — APPROVED** [review]
Due to the ptrace limitation this acts as a workaround. 
Although we might need to check more on this in the future,
(As there must be a reason for the extra signal to get generated)
but I'm good with this fix for now. Thanks!

**Review by ravindra-shinde2 — APPROVED** [review]

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp [hunk 1]
```diff
@@ -2000,7 +2000,19 @@ Status NativeProcessAIX::PtraceWrapper(int req, lldb::pid_t pid, void *addr,
...
       ptrace64(req, pid, (long long)addr, (int)data_size, (int *)result);
     } else if (req == PT_ATTACH) {
+      // Block SIGCHLD signal during attach to the process, 
+      // to prevent interruptions.
+      // The ptrace operation may send SIGCHLD signals in certain cases 
+      // during the attach, which can interfere. 
+      static sigset_t signal_set;
+      sigemptyset (&signal_set);
+      sigaddset (&signal_set, SIGCHLD);
+      pthread_sigmask( SIG_BLOCK, &signal_set, NULL );
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: 1. There is also sigthreadmask api? Are they different ?

2. In documentation they 3 errno's returned. Should we consider if any of these errors could occur ?
Please review once.
EFAULT | The set or old_set pointers are not in the process address space.
EINVAL | The value of the how parameter is not supported.
EPERM | The calling thread does not have the privilege to change the signal's mask

Comment (HemangGadhavi) [reply lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: 1. sigthreadmask and pthread_sigmask both are same. and other platform in LLDB also used same pthread_sigmask.

2. I have added logs for the failure case of both, and anyway errono is checked at line no 2029, so if any of the error  occur it would be checked.

**Review by ananthsureshkumar — APPROVED** [review]
