### PR TITLE
Offset correction

### LINKED ISSUE #65: Name of the process is missing
cpp file:-
—————
#include <iostream>

void triggerCrash() {
    int* ptr = nullptr;
    std::cout << "About to crash!" << std::endl;
    *ptr = 42;  // CRASH: Dereferencing null pointer
}

int main() {
    std::cout << "Program started" << std::endl;
    triggerCrash();
    std::cout << "Program finished" << std::endl;
    return 0;
}

How to compile:-
—————————
/opt/IBM/openxlC/17.1.2/bin/ibm-clang++_r -o crash crash.cpp -m64 -g

./crash

Logs :-
————

(139) root @ : /home/LLDB/package/aix-pre-release-0.5.x/bin
# lldb --core core
(lldb) target create --core "core"
Core file '/home/LLDB/package/aix-pre-release-0.5.x/bin/core' (powerpc64) was loaded.
(lldb) bt
* thread #1, stop reason = SIGSEGV ========>>> this line name is missing
  * frame #0: 0x0000000100000960 crash`triggerCrash() at crash.cpp:6
    frame #1: 0x0000000100000c3c crash`main at crash.cpp:11
    frame #2: 0x00000001000004ac crash`__start + 116
(lldb) process status
Process 18446744071562067993 stopped ========>>> this line also 
* thread #1, stop reason = SIGSEGV
    frame #0: 0x0000000100000960 crash`triggerCrash() at crash.cpp:6
   3   	void triggerCrash() {
   4   	    int* ptr = nullptr;
   5   	    std::cout << "About to crash!" << std::endl;
-> 6   	    *ptr = 42;  // CRASH: Dereferencing null pointer
   7   	}
   8
   9   	int main() {
(lldb) thread info ================>>>>>>>>>>> Here also
thread #1: tid = 0x101a4c374, 0x0000000100000960 crash`triggerCrash() at crash.cpp:6, stop reason = SIGSEGV
(lldb) q

### PR DESCRIPTION
**Pull request by DhruvSrivastavaX**
See PR 

- https://github.com/DhruvSrivastavaX/lldb-for-aix/pull/89 (closed)
- https://github.com/DhruvSrivastavaX/lldb-for-aix/pull/91

### CODE REVIEW

File: lldb/source/Plugins/Process/aix-core/AIXCore.cpp [hunk 1]
```diff
@@ -105,8 +105,9 @@ bool AIXCore64Header::ParseCoreHeader(lldb_private::DataExtractor &data,
     DataSize = data.GetU64(offset);
 
     *offset += 104;
-    lldb::offset_t offset_to_user = (*offset + sizeof(ThreadContext64));
+    //lldb::offset_t offset_to_user = (*offset + sizeof(ThreadContext64));
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/aix-core/AIXCore.cpp]: Why is this line commented? Can we remove if not required ?

File: lldb/source/Plugins/Process/aix-core/AIXCore.cpp [hunk 2]
```diff
@@ -105,8 +105,9 @@ bool AIXCore64Header::ParseCoreHeader(lldb_private::DataExtractor &data,
...
     int ret = 0;
+    lldb::offset_t offset_to_user = 1216;
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/aix-core/AIXCore.cpp]: Can we define 1216 as a macro and provide more description? .

File: lldb/source/Plugins/Process/aix-core/AIXCore.cpp (hunk 1 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/aix-core/AIXCore.cpp]: Done

File: lldb/source/Plugins/Process/aix-core/AIXCore.cpp (hunk 2 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/aix-core/AIXCore.cpp]: This is like other offsets used in this file.
I will be upgrading this entire logic for fall

Comment (ananthsureshkumar) [reply lldb/source/Plugins/Process/aix-core/AIXCore.cpp]: ok sure. Please track.

**Review by ravindra-shinde2 — APPROVED** [review]

File: lldb/source/Plugins/Process/aix-core/AIXCore.cpp (hunk 2 above)
Comment (ananthsureshkumar) [reply lldb/source/Plugins/Process/aix-core/AIXCore.cpp]: For now, please add a comment on why this offset 1216 .

Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/aix-core/AIXCore.cpp]: Yes, it is just taken from Ravi's mentioned PR. 
FYI @ravindra-shinde2

Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/aix-core/AIXCore.cpp]: Done

**Comment by DhruvSrivastavaX** [comment]
NOTE: This core file logic will be upgraded for Fall based on the community and internal inputs so that it can be recognised on other platforms as well and to avoid manual offsetting.

**Review by ananthsureshkumar — APPROVED** [review]

File: lldb/source/Plugins/Process/aix-core/AIXCore.cpp [hunk 3]
```diff
@@ -105,7 +105,12 @@ bool AIXCore64Header::ParseCoreHeader(lldb_private::DataExtractor &data,
     DataSize = data.GetU64(offset);
 
     *offset += 104;
-    lldb::offset_t offset_to_user = (*offset + sizeof(ThreadContext64));
+    // This offset calculation is due to the difference between
+    // AIX register size and LLDB register variables order.
+    // __context64 does not match RegContext
+    // To be modified
+    lldb::offset_t offset_to_user = (*offset + sizeof(__context64) +
```
Comment (HemangGadhavi) [inline lldb/source/Plugins/Process/aix-core/AIXCore.cpp:112]: Do we really need one more variable ? 
can't we increase the offset value it self after processing the ParseThreadContext(), and then parse to the ParseUserData() ?

Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/aix-core/AIXCore.cpp:112]: Yes agreed, we are doing this way because we are not parsing the complete thread data structure, 
then again we will have to do an offset jump like above (offset += 104)
Its temporary for now till fall

Comment (HemangGadhavi) [reply lldb/source/Plugins/Process/aix-core/AIXCore.cpp:112]: okay fine

**Review by HemangGadhavi — APPROVED** [review]
