### PR TITLE
Resolving coredump issue while attach with library calls

### LINKED ISSUE #9: Attach to AIX Process in LLDB
This issue is related to supporting the debugging of an attached process using LLDB on AIX.

Parent issue for all implementations going on for Attach in AIX 64-bit Process.

- [x] 1. Basic debugging support for Attached Process [Enhancement]
- [x] 2. Coredump issue when Libarary calls are involved in Attach Process debugging [Enhancement]
- [x] 3. LLDB is unable to recognise a process by PID in the first Attach trial [Bug]

Other bugs encountered in the process will be added as sub issues here.

### LINKED ISSUE #11: Resolving coredump issue when library calls are involved
Resolving coredump issue when library calls are involved

### LINKED ISSUE #19: core found with register read command in lldb
Justification for defect severity: Core gets generated while using ?register read? command in lldb debugger with using Openxl compiler ( 17.1.2.4 )

C file :-
======
#include<stdio.h>
int main()
{
	printf("Hello\n");
	int x=10;
	x++;
	printf("X value is = %d\n",x);
	x++;
	printf("X value is this time  = %d\n",x);
	return 0;
}

Compile method :-
===============
(0) root @ fvtfleet1-lp8: /home/Srikanth
# /opt/IBM/openxlC/17.1.2/bin/ibm-clang_r -g -o 1 1.c -m64

Below is the log from the machine where I got the core:-
==========================================

(0) root @ bosfleet2-lp10: /home/LLDB/lldb-for-aix
# /home/LLDB/lldb-for-aix/build-lldb/bin/lldb /home/LLDB/lldb-for-aix/1
(lldb) target create "/home/LLDB/lldb-for-aix/1"
Current executable set to '/home/LLDB/lldb-for-aix/1' (powerpc64).
(lldb) br main
"main" is not a valid subcommand of "breakpoint". Valid subcommands are: clear, command, delete, disable, enable, and others. Use "help breakpoint" to find out more.
(lldb) r
Process 8192634 launched: '/home/LLDB/lldb-for-aix/1' (powerpc64)
Hello
X value is = 11
X value is this time  = 12
Process 8192634 exited with status = 0 (0x00000000)
(lldb) b main
Breakpoint 1: where = 1`main + 28 at 1.c:4, address = 0x000000010000093c
(lldb) r
Process 33096072 launched: '/home/LLDB/lldb-for-aix/1' (powerpc64)
Process 33096072 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x000000010000093c 1`main at 1.c:4
   1   	#include<stdio.h>
   2   	int main()
   3   	{
-> 4   		printf("Hello\n");
   5   		int x=10;
   6   		x++;
   7   		printf("X value is = %d\n",x);
(lldb) n
Hello
Process 33096072 stopped
* thread #1, stop reason = step over
    frame #0: 0x0000000100000948 1`main at 1.c:5
   2   	int main()
   3   	{
   4   		printf("Hello\n");
-> 5   		int x=10;
   6   		x++;
   7   		printf("X value is = %d\n",x);
   8   		x++;
(lldb) rf v
error: 'rf' is not a valid command.
(lldb) fr v
(int) x = -1159983106
(lldb) n
Process 33096072 stopped
* thread #1, stop reason = step over
    frame #0: 0x0000000100000950 1`main at 1.c:6
   3   	{
   4   		printf("Hello\n");
   5   		int x=10;
-> 6   		x++;
   7   		printf("X value is = %d\n",x);
   8   		x++;
   9   		printf("X value is this time  = %d\n",x);
(lldb) fr v
(int) x = 10
(lldb) p x
(int) 10
(lldb) fr v x
(int) x = 10
(lldb) p x
(int) 10
(lldb) bt
* thread #1, stop reason = step over
  * frame #0: 0x0000000100000950 1`main at 1.c:6
    frame #1: 0x00000001000004ac 1`__start + 116
(lldb) bt all
* thread #1, stop reason = step over
  * frame #0: 0x0000000100000950 1`main at 1.c:6
    frame #1: 0x00000001000004ac 1`__start + 116
(lldb) register read
Assertion failed: GetModule().get(), file  /home/LLDB/lldb-for-aix/lldb/source/Core/Section.cpp, line 264, bool lldb_private::Section::ResolveContainedAddress(addr_t, Address &, bool) const()
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/LLDB/lldb-for-aix/build-lldb/bin/lldb /home/LLDB/lldb-for-aix/1
LLDB diagnostics will be written to /tmp/diagnostics-6536bc
Please include the directory content when filing a bug report
IOT/Abort trap(coredump)

(134) root @ bosfleet2-lp10: /home/LLDB/lldb-for-aix
# ls
.ci                     .github                 CONTRIBUTING.md         clang                   flang                   lld                     openmp                  utils
.clang-format           .gitignore              LICENSE.TXT             clang-tools-extra       libc                    lldb                    polly
.clang-tidy             .mailmap                README.md               cmake                   libclc                  llvm                    pstl
.git                    1                       SECURITY.md             compiler-rt             libcxx                  llvm-libgcc             pyproject.toml
.git-blame-ignore-revs  1.c                     bolt                    core                    libcxxabi               mlir                    runtimes
.gitattributes          CODE_OF_CONDUCT.md      build-lldb              cross-project-tests     libunwind               offload                 third-party

(0) root @ bosfleet2-lp10: /home/LLDB/lldb-for-aix
# file
Usage: file [-cdhi] [-M MagicFile] [-m MagicFile] [-f FileList]  [file...]

(2) root @ bosfleet2-lp10: /home/LLDB/lldb-for-aix
# file core
core: AIX core file fulldump 64-bit, lldb

(0) root @ bosfleet2-lp10: /home/LLDB/lldb-for-aix
# dbx -C core
Type 'help' for help.
warning: Object file is not specified, and the object file "lldb" mentioned in
 the core file doesn't exist in the current directory or doesn't match with
 the core file (ignored). Some info may not be available.
[using memory image in core]
reading symbolic information ...warning: cannot open lldb
warning: no source compiled with -g

IOT/Abort trap in pthread_kill at 0x9000000006c7304 ($t1)
0x9000000006c7304 (pthread_kill+0xa4) e8410028             ld   r2,0x28(r1)
(dbx) t
pthread_kill(??, ??) at 0x9000000006c7304
_p_raise(??) at 0x9000000006c6b84
.() at 0x100002834 [inaccessible: missing lldb]
pthread_kill(??, ??) at 0x9000000006c7304
_p_raise(??) at 0x9000000006c6b84
raise.raise(??) at 0x900000000252448
abort() at 0x9000000002d1360
__assert_c99(??, ??, ??, ??) at 0x9000000002d1158
.() at 0x100892418 [inaccessible: missing lldb]
.() at 0x100891d20 [inaccessible: missing lldb]
.() at 0x10088fd48 [inaccessible: missing lldb]
.() at 0x10088fc60 [inaccessible: missing lldb]
.() at 0x106efc754 [inaccessible: missing lldb]
.() at 0x106efc27c [inaccessible: missing lldb]
.() at 0x106efc000 [inaccessible: missing lldb]
.() at 0x106861778 [inaccessible: missing lldb]
.() at 0x10686d33c [inaccessible: missing lldb]
.() at 0x106de9068 [inaccessible: missing lldb]
.() at 0x106dec610 [inaccessible: missing lldb]
.() at 0x106aba3fc [inaccessible: missing lldb]
.() at 0x105f3d764 [inaccessible: missing lldb]
.() at 0x107009534 [inaccessible: missing lldb]
.() at 0x10700be24 [inaccessible: missing lldb]
.() at 0x107002a90 [inaccessible: missing lldb]
(dbx) Read from remote host c291f5u32hmc.pok.stglabs.ibm.com: Operation timed out
Connection to c291f5u32hmc.pok.stglabs.ibm.com closed.

  

    < Note by srtiwari (Tiwari, Srikanth), 2025/02/17 00:21:10, seq: 3 rel: 0  action: note>
Getting the same core dump with step command of lldb also, below is the log ( information on how to re-produce ). Here also the compiler is Openxl-17.1.2.4
------------------------------------------------------------------------------------------------------------------------------------------------------------

(0) root @ bosfleet2-lp10: /home/LLDB/lldb-for-aix
# /home/LLDB/lldb-for-aix/build-lldb/bin/lldb /home/LLDB/lldb-for-aix/1
(lldb) target create "/home/LLDB/lldb-for-aix/1"
Current executable set to '/home/LLDB/lldb-for-aix/1' (powerpc64).
(lldb) b main
Breakpoint 1: where = 1`main + 28 at 1.c:4, address = 0x000000010000093c
(lldb) r
Process 28115282 launched: '/home/LLDB/lldb-for-aix/1' (powerpc64)
Process 28115282 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x000000010000093c 1`main at 1.c:4
   1   	#include<stdio.h>
   2   	int main()
   3   	{
-> 4   		printf("Hello\n");
   5   		int x=10;
   6   		x++;
   7   		printf("X value is = %d\n",x);
(lldb) s
Process 28115282 stopped
* thread #1, stop reason = step in failed (Could not create return address breakpoint. Return address (0x100000944) did not point to executable memory.)
    frame #0: 0x00000001000009c0 1`printf
1`printf:
->  0x1000009c0 <+0>:  ld     12, 200(2)
    0x1000009c4 <+4>:  std    2, 40(1)
    0x1000009c8 <+8>:  ld     0, 0(12)
    0x1000009cc <+12>: ld     2, 8(12)
(lldb) s
Process 28115282 stopped
* thread #1, stop reason = instruction step into
    frame #0: 0x00000001000009c4 1`printf + 4
1`printf:
->  0x1000009c4 <+4>:  std    2, 40(1)
    0x1000009c8 <+8>:  ld     0, 0(12)
    0x1000009cc <+12>: ld     2, 8(12)
    0x1000009d0 <+16>: mtctr  0
(lldb) s
Process 28115282 stopped
* thread #1, stop reason = instruction step into
    frame #0: 0x00000001000009c8 1`printf + 8
1`printf:
->  0x1000009c8 <+8>:  ld     0, 0(12)
    0x1000009cc <+12>: ld     2, 8(12)
    0x1000009d0 <+16>: mtctr  0
    0x1000009d4 <+20>: bctr
(lldb) s
Process 28115282 stopped
* thread #1, stop reason = instruction step into
    frame #0: 0x00000001000009cc 1`printf + 12
1`printf:
->  0x1000009cc <+12>: ld     2, 8(12)
    0x1000009d0 <+16>: mtctr  0
    0x1000009d4 <+20>: bctr
    0x1000009d8 <+24>: .long  0x00000000                ; unknown opcode
(lldb) s
Process 28115282 stopped
* thread #1, stop reason = instruction step into
    frame #0: 0x00000001000009d0 1`printf + 16
1`printf:
->  0x1000009d0 <+16>: mtctr  0
    0x1000009d4 <+20>: bctr
    0x1000009d8 <+24>: .long  0x00000000                ; unknown opcode
    0x1000009dc <+28>: .long  0x000ca000                ; unknown opcode
(lldb) s
Process 28115282 stopped
* thread #1, stop reason = instruction step into
    frame #0: 0x00000001000009d4 1`printf + 20
1`printf:
->  0x1000009d4 <+20>: bctr
    0x1000009d8 <+24>: .long  0x00000000                ; unknown opcode
    0x1000009dc <+28>: .long  0x000ca000                ; unknown opcode
    0x1000009e0 <+32>: .long  0x00000000                ; unknown opcode
(lldb) s
Assertion failed: GetModule().get(), file  /home/LLDB/lldb-for-aix/lldb/source/Core/Section.cpp, line 264, bool lldb_private::Section::ResolveContainedAddress(addr_t, Address &, bool) const()
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
LLDB diagnostics will be written to /tmp/diagnostics-b8ccc7
Please include the directory content when filing a bug report
IOT/Abort trap(coredump)

(134) root @ bosfleet2-lp10: /home/LLDB/lldb-for-aix
# file core
core: AIX core file fulldump 64-bit, lldb

(0) root @ bosfleet2-lp10: /home/LLDB/lldb-for-aix
# dbx -C core
Type 'help' for help.
warning: Object file is not specified, and the object file "lldb" mentioned in
 the core file doesn't exist in the current directory or doesn't match with
 the core file (ignored). Some info may not be available.
[using memory image in core]
reading symbolic information ...warning: cannot open lldb
warning: no source compiled with -g

IOT/Abort trap in pthread_kill at 0x9000000006c7304 ($t15)
0x9000000006c7304 (pthread_kill+0xa4) e8410028             ld   r2,0x28(r1)
(dbx) t
pthread_kill(??, ??) at 0x9000000006c7304
_p_raise(??) at 0x9000000006c6b84
.() at 0x100002834 [inaccessible: missing lldb]
pthread_kill(??, ??) at 0x9000000006c7304
_p_raise(??) at 0x9000000006c6b84
raise.raise(??) at 0x900000000252448
abort() at 0x9000000002d1360
__assert_c99(??, ??, ??, ??) at 0x9000000002d1158
.() at 0x100892418 [inaccessible: missing lldb]
.() at 0x100891d20 [inaccessible: missing lldb]
.() at 0x10088fd48 [inaccessible: missing lldb]
.() at 0x10088fc60 [inaccessible: missing lldb]
.() at 0x1009238fc [inaccessible: missing lldb]
.() at 0x10552f920 [inaccessible: missing lldb]
.() at 0x1054fedc0 [inaccessible: missing lldb]
.() at 0x1054fe4a8 [inaccessible: missing lldb]
.() at 0x1055332f4 [inaccessible: missing lldb]
.() at 0x10392be9c [inaccessible: missing lldb]
.() at 0x10392b63c [inaccessible: missing lldb]
.() at 0x1054bb5d4 [inaccessible: missing lldb]
.() at 0x1054e7510 [inaccessible: missing lldb]
.() at 0x100905e6c [inaccessible: missing lldb]
.() at 0x100905b68 [inaccessible: missing lldb]
.() at 0x100902df0 [inaccessible: missing lldb]
.() at 0x1009018a8 [inaccessible: missing lldb]
.() at 0x1008ff5a8 [inaccessible: missing lldb]
.() at 0x1008fe928 [inaccessible: missing lldb]
.() at 0x1008c5844 [inaccessible: missing lldb]
.() at 0x1008c4df8 [inaccessible: missing lldb]
.() at 0x1065ed824 [inaccessible: missing lldb]
(dbx) where
pthread_kill(??, ??) at 0x9000000006c7304
_p_raise(??) at 0x9000000006c6b84
.() at 0x100002834 [inaccessible: missing lldb]
pthread_kill(??, ??) at 0x9000000006c7304
_p_raise(??) at 0x9000000006c6b84
raise.raise(??) at 0x900000000252448
abort() at 0x9000000002d1360
__assert_c99(??, ??, ??, ??) at 0x9000000002d1158
.() at 0x100892418 [inaccessible: missing lldb]
.() at 0x100891d20 [inaccessible: missing lldb]
.() at 0x10088fd48 [inaccessible: missing lldb]
.() at 0x10088fc60 [inaccessible: missing lldb]
.() at 0x1009238fc [inaccessible: missing lldb]
.() at 0x10552f920 [inaccessible: missing lldb]
.() at 0x1054fedc0 [inaccessible: missing lldb]
.() at 0x1054fe4a8 [inaccessible: missing lldb]
.() at 0x1055332f4 [inaccessible: missing lldb]
.() at 0x10392be9c [inaccessible: missing lldb]
.() at 0x10392b63c [inaccessible: missing lldb]
.() at 0x1054bb5d4 [inaccessible: missing lldb]
.() at 0x1054e7510 [inaccessible: missing lldb]
.() at 0x100905e6c [inaccessible: missing lldb]
.() at 0x100905b68 [inaccessible: missing lldb]
.() at 0x100902df0 [inaccessible: missing lldb]
.() at 0x1009018a8 [inaccessible: missing lldb]
.() at 0x1008ff5a8 [inaccessible: missing lldb]
.() at 0x1008fe928 [inaccessible: missing lldb]
.() at 0x1008c5844 [inaccessible: missing lldb]
.() at 0x1008c4df8 [inaccessible: missing lldb]
.() at 0x1065ed824 [inaccessible: missing lldb]

    < Note by srtiwari (Tiwari, Srikanth), 2025/02/17 00:36:02, seq: 4 rel: 0  action: note>
--------------------------------------------------------------------------------------------------------------------------------------------------
Got one more core with next command of lldb also, below is the log ( information on how to re-produce ). Here also the compiler is Openxl-17.1.2.4
--------------------------------------------------------------------------------------------------------------------------------------------------
In this core also the stack information is same......

(0) root @ bosfleet2-lp10: /home/LLDB/lldb-for-aix
# /home/LLDB/lldb-for-aix/build-lldb/bin/lldb /home/LLDB/lldb-for-aix/1
(lldb) target create "/home/LLDB/lldb-for-aix/1"
Current executable set to '/home/LLDB/lldb-for-aix/1' (powerpc64).
(lldb) b main
Breakpoint 1: where = 1`main + 28 at 1.c:4, address = 0x000000010000093c
(lldb) r
Process 8192628 launched: '/home/LLDB/lldb-for-aix/1' (powerpc64)
Process 8192628 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x000000010000093c 1`main at 1.c:4
   1   	#include<stdio.h>
   2   	int main()
   3   	{
-> 4   		printf("Hello\n");
   5   		int x=10;
   6   		x++;
   7   		printf("X value is = %d\n",x);
(lldb) n
Hello
Process 8192628 stopped
* thread #1, stop reason = step over
    frame #0: 0x0000000100000948 1`main at 1.c:5
   2   	int main()
   3   	{
   4   		printf("Hello\n");
-> 5   		int x=10;
   6   		x++;
   7   		printf("X value is = %d\n",x);
   8   		x++;
(lldb) n
Process 8192628 stopped
* thread #1, stop reason = step over
    frame #0: 0x0000000100000950 1`main at 1.c:6
   3   	{
   4   		printf("Hello\n");
   5   		int x=10;
-> 6   		x++;
   7   		printf("X value is = %d\n",x);
   8   		x++;
   9   		printf("X value is this time  = %d\n",x);
(lldb) n
Process 8192628 stopped
* thread #1, stop reason = step over
    frame #0: 0x000000010000095c 1`main at 1.c:7
   4   		printf("Hello\n");
   5   		int x=10;
   6   		x++;
-> 7   		printf("X value is = %d\n",x);
   8   		x++;
   9   		printf("X value is this time  = %d\n",x);
   10  		return 0;
(lldb) n
X value is = 11
Process 8192628 stopped
* thread #1, stop reason = step over
    frame #0: 0x0000000100000970 1`main at 1.c:8
   5   		int x=10;
   6   		x++;
   7   		printf("X value is = %d\n",x);
-> 8   		x++;
   9   		printf("X value is this time  = %d\n",x);
   10  		return 0;
   11  	}
(lldb) n
Process 8192628 stopped
* thread #1, stop reason = step over
    frame #0: 0x000000010000097c 1`main at 1.c:9
   6   		x++;
   7   		printf("X value is = %d\n",x);
   8   		x++;
-> 9   		printf("X value is this time  = %d\n",x);
   10  		return 0;
   11  	}
(lldb) n
X value is this time  = 12
Process 8192628 stopped
* thread #1, stop reason = step over
    frame #0: 0x0000000100000990 1`main at 1.c:10
   7   		printf("X value is = %d\n",x);
   8   		x++;
   9   		printf("X value is this time  = %d\n",x);
-> 10  		return 0;
   11  	}
(lldb) n
Process 8192628 stopped
* thread #1, stop reason = step over
    frame #0: 0x00000001000004ac 1`__start + 116
1`__start:
->  0x1000004ac <+116>: nop
    0x1000004b0 <+120>: lwz    7, 24(2)
    0x1000004b4 <+124>: cmpwi  7, 0
    0x1000004b8 <+128>: bt     2, 0x1000004c0
(lldb) n
Process 8192628 stopped
* thread #1, stop reason = instruction step over
    frame #0: 0x00000001000004b0 1`__start + 120
1`__start:
->  0x1000004b0 <+120>: lwz    7, 24(2)
    0x1000004b4 <+124>: cmpwi  7, 0
    0x1000004b8 <+128>: bt     2, 0x1000004c0
    0x1000004bc <+132>: lwz    3, 28(2)
(lldb) n
Process 8192628 stopped
* thread #1, stop reason = instruction step over
    frame #0: 0x00000001000004b4 1`__start + 124
1`__start:
->  0x1000004b4 <+124>: cmpwi  7, 0
    0x1000004b8 <+128>: bt     2, 0x1000004c0
    0x1000004bc <+132>: lwz    3, 28(2)
    0x1000004c0 <+136>: bl     0x1000008f8
(lldb) n
Process 8192628 stopped
* thread #1, stop reason = instruction step over
    frame #0: 0x00000001000004b8 1`__start + 128
1`__start:
->  0x1000004b8 <+128>: bt     2, 0x1000004c0
    0x1000004bc <+132>: lwz    3, 28(2)
    0x1000004c0 <+136>: bl     0x1000008f8
    0x1000004c4 <+140>: ld     2, 40(1)
(lldb) n
Process 8192628 stopped
* thread #1, stop reason = instruction step over
    frame #0: 0x00000001000004c0 1`__start + 136
1`__start:
->  0x1000004c0 <+136>: bl     0x1000008f8
    0x1000004c4 <+140>: ld     2, 40(1)
    0x1000004c8 <+144>: tweq   1, 1
    0x1000004cc <+148>: .long  0x00000000                ; unknown opcode
(lldb) n
Assertion failed: GetModule().get(), file  /home/LLDB/lldb-for-aix/lldb/source/Core/Section.cpp, line 264, bool lldb_private::Section::ResolveContainedAddress(addr_t, Address &, bool) const()
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
LLDB diagnostics will be written to /tmp/diagnostics-08d588
Please include the directory content when filing a bug report
IOT/Abort trap(coredump)

(134) root @ bosfleet2-lp10: /home/LLDB/lldb-for-aix
# dbx -C core
Type 'help' for help.
warning: Object file is not specified, and the object file "lldb" mentioned in
 the core file doesn't exist in the current directory or doesn't match with
 the core file (ignored). Some info may not be available.
[using memory image in core]
reading symbolic information ...warning: cannot open lldb
warning: no source compiled with -g

IOT/Abort trap in pthread_kill at 0x9000000006c7304 ($t16)
0x9000000006c7304 (pthread_kill+0xa4) e8410028             ld   r2,0x28(r1)
(dbx) t
pthread_kill(??, ??) at 0x9000000006c7304
_p_raise(??) at 0x9000000006c6b84
.() at 0x100002834 [inaccessible: missing lldb]
pthread_kill(??, ??) at 0x9000000006c7304
_p_raise(??) at 0x9000000006c6b84
raise.raise(??) at 0x900000000252448
abort() at 0x9000000002d1360
__assert_c99(??, ??, ??, ??) at 0x9000000002d1158
.() at 0x100892418 [inaccessible: missing lldb]
.() at 0x100891d20 [inaccessible: missing lldb]
.() at 0x10088fd48 [inaccessible: missing lldb]
.() at 0x10088fc60 [inaccessible: missing lldb]
.() at 0x1009238fc [inaccessible: missing lldb]
.() at 0x10552f920 [inaccessible: missing lldb]
.() at 0x1054fedc0 [inaccessible: missing lldb]
.() at 0x1054fe4a8 [inaccessible: missing lldb]
.() at 0x1055332f4 [inaccessible: missing lldb]
.() at 0x10392be9c [inaccessible: missing lldb]
.() at 0x10392b63c [inaccessible: missing lldb]
.() at 0x1054bb5d4 [inaccessible: missing lldb]
.() at 0x1054e7510 [inaccessible: missing lldb]
.() at 0x100905e6c [inaccessible: missing lldb]
.() at 0x100905b68 [inaccessible: missing lldb]
.() at 0x100902df0 [inaccessible: missing lldb]
.() at 0x1009018a8 [inaccessible: missing lldb]
.() at 0x1008ff5a8 [inaccessible: missing lldb]
.() at 0x1008fe928 [inaccessible: missing lldb]
.() at 0x1008c5844 [inaccessible: missing lldb]
.() at 0x1008c4df8 [inaccessible: missing lldb]
.() at 0x1065ed824 [inaccessible: missing lldb]

    < Note by srtiwari (Tiwari, Srikanth), 2025/02/19 03:08:12, seq: 5 rel: 0  action: note>
Below log is from dbx, works fine there

(0) root @ bosfleet2-lp10: /home/LLDB/lldb-for-aix
# dbx 1
Type 'help' for help.
reading symbolic information ...
(dbx) st in main
[1] stop in main
(dbx) r
[1] stopped in main at line 4 ($t1)
    4   	printf("Hello\n");
(dbx) n
Hello
stopped in main at line 5 ($t1)
    5   	int x=10;
(dbx) register read
register read
^ unrecognized command
(dbx) registers
  $r0:0x09000000006d7e80  $stkp:0x0ffffffffffff760   $toc:0x0000000110000ca0
  $r3:0x0000000000000006    $r4:0x0000000110003238    $r5:0x0000000000000008
  $r6:0x0000000000000000    $r7:0x0000000000000000    $r8:0x0000000012430267
  $r9:0x0000000012430267   $r10:0x0000000000000000   $r11:0x0000000000000000
 $r12:0x0000000100000944   $r13:0x000000011000b0c0   $r14:0x0000000000000001
 $r15:0x0ffffffffffff850   $r16:0x0ffffffffffff860   $r17:0x0800200140000000
 $r18:0x0ffffffffffffed0   $r19:0x09fffffff00107b0   $r20:0xbadc0ffee0ddf00d
 $r21:0xbadc0ffee0ddf00d   $r22:0xbadc0ffee0ddf00d   $r23:0xbadc0ffee0ddf00d
 $r24:0xbadc0ffee0ddf00d   $r25:0xbadc0ffee0ddf00d   $r26:0xbadc0ffee0ddf00d
 $r27:0xbadc0ffee0ddf00d   $r28:0xbadc0ffee0ddf00d   $r29:0xbadc0ffee0ddf00d
 $r30:0xbadc0ffee0ddf00d   $r31:0x0ffffffffffff760
 $iar:0x0000000100000948   $msr:0x800000000000d032    $cr:0x22200248
$link:0x0000000100000944   $ctr:0x09000000006d7e80   $xer:0x00000006

          Condition status = 0:e 1:e 2:e 5:e 6:g 7:l
	[unset $noflregs to view floating point registers]
	[unset $novregs to view vector registers]
	[unset $novsregs to view vector scalar registers]
in main at line 5 ($t1)
0x100000948 (main+0x28) 3860000a             li   r3,0xa
(dbx) q

### PR DESCRIPTION
**Pull request by HemangGadhavi**
Resolving coredump issue while attach with library calls.

The issue is because of the split libc in to two modules (shr_64.o & _shr_64.o) in AIX.

The LLDB was only loading one module at a time without comparing object name. 
Added changes to compare and load both module. 

Before Fix:
-----------------
(lldb) image list
[  0]                                                         /LLDB/hemang/testcase/t2 
[  1]                                                         /usr/ccs/bin/usla64 
[  2]                                                         /usr/lib/libcrypt.a (shr_64.o)
[  3]                                                         /usr/lib/libpthreads.a (shr_xpg5_64.o)
[  4]                                                         /usr/lib/libc.a (shr_64.o)

After Fix:
---------
(lldb) image list
[  0]                                                         /LLDB/hemang/testcase/t2 
[  1]                                                         /usr/ccs/bin/usla64 
[  2]                                                         /usr/lib/libpthreads.a (_shr_xpg5_64.o)
[  3]                                                         /usr/lib/libcrypt.a (shr_64.o)
[  4]                                                         /usr/lib/libc.a (_shr_64.o)
[  5]                                                         /usr/lib/libpthreads.a (shr_xpg5_64.o)
[  6]                                                         /usr/lib/libc.a (shr_64.o)

### CODE REVIEW

File: lldb/source/Core/ModuleList.cpp [hunk 1]
```diff
@@ -260,6 +260,16 @@ void ModuleList::ReplaceEquivalent(
...
+ 
+    // To remove the exact equivalent module, the object name must be 
+    // specified. When the equivalent_module_spec object is created, its 
+    // object name is initially set to NULL. This is because the module_sp's 
+    // GetPath() returns a path in the format (/usr/ccs/libc.a), which does 
+    // not include the object name. As a result, MatchesModuleSpec may return 
+    // true even though the object name is NULL and doesn't match any loaded 
+    // module. To fix this, set the object name of the equivalent_module_spec 
+    // to be the same as the object name of the module_sp. */
+    equivalent_module_spec.SetObjectName(module_sp->GetObjectName());
```
Comment (DhruvSrivastavaX) [inline lldb/source/Core/ModuleList.cpp:272]: Since this is a common code you can put ` #ifdef _AIX` in this call. Not needed for the definition though.

Comment (DhruvSrivastavaX) [reply lldb/source/Core/ModuleList.cpp:272]: Or if there is a better if check condition specific to aix that will be good too.

Comment (ananthsureshkumar) [inline lldb/source/Core/ModuleList.cpp:272]: Pls add _AIX check.

Comment (HemangGadhavi) [reply lldb/source/Core/ModuleList.cpp:272]: Added the #ifdef _AIX

**Comment by DhruvSrivastavaX** [comment]
Please add some description about the issue and fix in the PR. 
Changes are good to go.

File: lldb/source/Core/ModuleList.cpp (hunk 1 above)
Comment (HemangGadhavi) [reply lldb/source/Core/ModuleList.cpp:272]: Already added

**Review by ananthsureshkumar — APPROVED** [review]

**Review by DhruvSrivastavaX — APPROVED** [review]

**Comment by DhruvSrivastavaX** [comment]
A point to note is that this half loading problem due to split library also existed with executables, but
it did not directly cause a coredump in most sessions. 
This fix commonly solves that problem as well.

**Comment by DhruvSrivastavaX** [comment]
A point to note is that this half loading problem due to split library also existed with executables, but
it did not directly cause a coredump in most sessions. 
This fix beautifully solves that problem as well.
