### PR TITLE
disassembly fix for symbol resolution with branch statements.

### LINKED ISSUE #130: Branch targets not displayed in disassembly
The branch targets should show the target symbol info such as the function name, file, line number etc, but that info is empty.
```
# bin/lldb ../tests/1189804   
(lldb) target create "../tests/1189804"
Current executable set to '/home/dhruv/LLDB/tests/1189804' (powerpc64).
(lldb) b main
Breakpoint 1: where = 1189804`main + 28 at 1189804.c:24, address = 0x00000001000008b4
(lldb) r
Process 27591116 launched: '/home/dhruv/LLDB/tests/1189804' (powerpc64)
Process 27591116 stopped
* thread #1, name = '1189804', stop reason = breakpoint 1.1
    frame #0: 0x00000001000008b4 1189804`main at 1189804.c:24
   21       int choice;
   22  
   23       // Modify and print union data
-> 24       printf("Enter 1 for int, 2 for float, 3 for string: ");
   25       scanf("%d", &choice);
   26       modifyUnion(&data, choice);
   27       printUnion(&data);
(lldb) di
1189804`main:
    0x100000898 <+0>:   mflr   0
    0x10000089c <+4>:   std    31, -8(1)
    0x1000008a0 <+8>:   std    0, 16(1)
    0x1000008a4 <+12>:  stdu   1, -176(1)
    0x1000008a8 <+16>:  mr     31, 1
    0x1000008ac <+20>:  li     3, 0
    0x1000008b0 <+24>:  stw    3, 164(31)
->  0x1000008b4 <+28>:  ld     3, 176(2)
    0x1000008b8 <+32>:  bl     0x100000da8  
    0x1000008bc <+36>:  ld     2, 40(1)
    0x1000008c0 <+40>:  ld     3, 192(2)
    0x1000008c4 <+44>:  addi   4, 31, 140
    0x1000008c8 <+48>:  bl     0x100000dd0  
    0x1000008cc <+52>:  ld     2, 40(1)
    0x1000008d0 <+56>:  lwz    3, 140(31)
    0x1000008d4 <+60>:  extsw  4, 3
    0x1000008d8 <+64>:  addi   3, 31, 144
    0x1000008dc <+68>:  bl     0x1000009a8 
    0x1000008e0 <+72>:  nop    
    0x1000008e4 <+76>:  addi   3, 31, 144
    0x1000008e8 <+80>:  bl     0x100000a88 
    0x1000008ec <+84>:  nop    
    ...
```

### PR DESCRIPTION
**Pull request by DhruvSrivastavaX**
Without fix:
```
# bin/lldb ../tests/1189804   
(lldb) target create "../tests/1189804"
Current executable set to '/home/dhruv/LLDB/tests/1189804' (powerpc64).
(lldb) b main
Breakpoint 1: where = 1189804`main + 28 at 1189804.c:24, address = 0x00000001000008b4
(lldb) r
Process 27591116 launched: '/home/dhruv/LLDB/tests/1189804' (powerpc64)
Process 27591116 stopped
* thread #1, name = '1189804', stop reason = breakpoint 1.1
    frame #0: 0x00000001000008b4 1189804`main at 1189804.c:24
   21       int choice;
   22  
   23       // Modify and print union data
-> 24       printf("Enter 1 for int, 2 for float, 3 for string: ");
   25       scanf("%d", &choice);
   26       modifyUnion(&data, choice);
   27       printUnion(&data);
(lldb) di
1189804`main:
    0x100000898 <+0>:   mflr   0
    0x10000089c <+4>:   std    31, -8(1)
    0x1000008a0 <+8>:   std    0, 16(1)
    0x1000008a4 <+12>:  stdu   1, -176(1)
    0x1000008a8 <+16>:  mr     31, 1
    0x1000008ac <+20>:  li     3, 0
    0x1000008b0 <+24>:  stw    3, 164(31)
->  0x1000008b4 <+28>:  ld     3, 176(2)
    0x1000008b8 <+32>:  bl     0x100000da8  
    0x1000008bc <+36>:  ld     2, 40(1)
    0x1000008c0 <+40>:  ld     3, 192(2)
    0x1000008c4 <+44>:  addi   4, 31, 140
    0x1000008c8 <+48>:  bl     0x100000dd0  
    0x1000008cc <+52>:  ld     2, 40(1)
    0x1000008d0 <+56>:  lwz    3, 140(31)
    0x1000008d4 <+60>:  extsw  4, 3
    0x1000008d8 <+64>:  addi   3, 31, 144
    0x1000008dc <+68>:  bl     0x1000009a8 
    0x1000008e0 <+72>:  nop    
    0x1000008e4 <+76>:  addi   3, 31, 144
    0x1000008e8 <+80>:  bl     0x100000a88 
    0x1000008ec <+84>:  nop    
    ...
```

With fix:

```
# bin/lldb ../tests/1189804   
(lldb) target create "../tests/1189804"
Current executable set to '/home/dhruv/LLDB/tests/1189804' (powerpc64).
(lldb) b main
Breakpoint 1: where = 1189804`main + 28 at 1189804.c:24, address = 0x00000001000008b4
(lldb) r
Process 27591116 launched: '/home/dhruv/LLDB/tests/1189804' (powerpc64)
Process 27591116 stopped
* thread #1, name = '1189804', stop reason = breakpoint 1.1
    frame #0: 0x00000001000008b4 1189804`main at 1189804.c:24
   21       int choice;
   22  
   23       // Modify and print union data
-> 24       printf("Enter 1 for int, 2 for float, 3 for string: ");
   25       scanf("%d", &choice);
   26       modifyUnion(&data, choice);
   27       printUnion(&data);
(lldb) di
1189804`main:
    0x100000898 <+0>:   mflr   0
    0x10000089c <+4>:   std    31, -8(1)
    0x1000008a0 <+8>:   std    0, 16(1)
    0x1000008a4 <+12>:  stdu   1, -176(1)
    0x1000008a8 <+16>:  mr     31, 1
    0x1000008ac <+20>:  li     3, 0
    0x1000008b0 <+24>:  stw    3, 164(31)
->  0x1000008b4 <+28>:  ld     3, 176(2)
    0x1000008b8 <+32>:  bl     0x100000da8               ; symbol stub for: printf
    0x1000008bc <+36>:  ld     2, 40(1)
    0x1000008c0 <+40>:  ld     3, 192(2)
    0x1000008c4 <+44>:  addi   4, 31, 140
    0x1000008c8 <+48>:  bl     0x100000dd0               ; symbol stub for: scanf
    0x1000008cc <+52>:  ld     2, 40(1)
    0x1000008d0 <+56>:  lwz    3, 140(31)
    0x1000008d4 <+60>:  extsw  4, 3
    0x1000008d8 <+64>:  addi   3, 31, 144
    0x1000008dc <+68>:  bl     0x1000009a8               ; modifyUnion at 1189804.c:63
    0x1000008e0 <+72>:  nop    
    0x1000008e4 <+76>:  addi   3, 31, 144
    0x1000008e8 <+80>:  bl     0x100000a88               ; printUnion at 1189804.c:45
    0x1000008ec <+84>:  nop    
    ...
```

### CODE REVIEW

**Review by ananthsureshkumar — APPROVED** [review]

File: lldb/source/Plugins/Disassembler/LLVMC/DisassemblerLLVMC.cpp [hunk 1]
```diff
@@ -1381,6 +1384,37 @@ void DisassemblerLLVMC::MCDisasmInstance::PrintMCInst(
...
+  SymbolContext sym_ctx;
+  Address target_address;
+  for (unsigned i = 0; i < mc_inst.getNumOperands(); ++i) {
+    const auto &op = mc_inst.getOperand(i);
+    const llvm::MCInstrDesc &desc = m_instr_info_up->get(mc_inst.getOpcode());
+    if (desc.isBranch() || desc.isCall()) {
+      Target *target =
+          m_owner.m_exe_ctx ? m_owner.m_exe_ctx->GetTargetPtr() : nullptr;
+      if (op.isImm()) {
+        lldb::addr_t target_addr = (lldb::addr_t)(pc + (op.getImm() << 2));
```
Comment (HemangGadhavi) [inline lldb/source/Plugins/Disassembler/LLVMC/DisassemblerLLVMC.cpp:1404]: If you can just add the comment why left shift is required, that will be help full for ref.

**Review by HemangGadhavi — APPROVED** [review]

**Review by Niranjan-bos — APPROVED** [review]

**Review by ravindra-shinde2 — APPROVED** [review]

**Comment by DhruvSrivastavaX** [comment]
Merging since these are just cosmetic changes and the PR is approved.
