### PR TITLE
Fix: Corrected offset to retrieve process name and process ID

### LINKED ISSUE #65: Name of the process is missing
cpp file:-
—————
#include <iostream>

void triggerCrash() {
    int* ptr = nullptr;
    std::cout << "About to crash!" << std::endl;
    *ptr = 42;  // CRASH: Dereferencing null pointer
}

int main() {
    std::cout << "Program started" << std::endl;
    triggerCrash();
    std::cout << "Program finished" << std::endl;
    return 0;
}

How to compile:-
—————————
/opt/IBM/openxlC/17.1.2/bin/ibm-clang++_r -o crash crash.cpp -m64 -g

./crash

Logs :-
————

(139) root @ : /home/LLDB/package/aix-pre-release-0.5.x/bin
# lldb --core core
(lldb) target create --core "core"
Core file '/home/LLDB/package/aix-pre-release-0.5.x/bin/core' (powerpc64) was loaded.
(lldb) bt
* thread #1, stop reason = SIGSEGV ========>>> this line name is missing
  * frame #0: 0x0000000100000960 crash`triggerCrash() at crash.cpp:6
    frame #1: 0x0000000100000c3c crash`main at crash.cpp:11
    frame #2: 0x00000001000004ac crash`__start + 116
(lldb) process status
Process 18446744071562067993 stopped ========>>> this line also 
* thread #1, stop reason = SIGSEGV
    frame #0: 0x0000000100000960 crash`triggerCrash() at crash.cpp:6
   3   	void triggerCrash() {
   4   	    int* ptr = nullptr;
   5   	    std::cout << "About to crash!" << std::endl;
-> 6   	    *ptr = 42;  // CRASH: Dereferencing null pointer
   7   	}
   8
   9   	int main() {
(lldb) thread info ================>>>>>>>>>>> Here also
thread #1: tid = 0x101a4c374, 0x0000000100000960 crash`triggerCrash() at crash.cpp:6, stop reason = SIGSEGV
(lldb) q

### PR DESCRIPTION
**Pull request by ravindra-shinde2**
Corrected the offset to parse the process info (PID, Process Name)

**# Without fix:**

# build/bin/lldb -c /home/ravi/lldb_tests/core 
(lldb) target create --core "/home/ravi/lldb_tests/core"
Core file '/home/ravi/lldb_tests/core' (powerpc64) was loaded.
(lldb) bt
* thread #1, stop reason = SIGSEGV
  * frame #0: 0x0000000100000980 2testingcore`main at 1190304_short_testcase.c:8
    frame #1: 0x00000001000004ac 2testingcore`__start + 116
(lldb) process status
Process 18446744071562067992 stopped
* thread #1, stop reason = SIGSEGV
    frame #0: 0x0000000100000980 2testingcore`main at 1190304_short_testcase.c:8
   5         int x = 42;
   6         int *p = NULL;
   7         printf("pid[0x%x] ppid[0x%x]\n", getpid(), getppid());
-> 8         *p = x;  // Intentional crash
   9         return 0;
   10    }
(lldb) 

**# With Fix:**

# build/bin/lldb -c /home/ravi/lldb_tests/core 
(lldb) target create --core "/home/ravi/lldb_tests/core"
Core file '/home/ravi/lldb_tests/core' (powerpc64) was loaded.
(lldb) bt
* thread #1, name = '2testingcore', stop reason = SIGSEGV
  * frame #0: 0x0000000100000980 2testingcore`main at 1190304_short_testcase.c:8
    frame #1: 0x00000001000004ac 2testingcore`__start + 116
(lldb) process status
Process 35848570 stopped
* thread #1, name = '2testingcore', stop reason = SIGSEGV
    frame #0: 0x0000000100000980 2testingcore`main at 1190304_short_testcase.c:8
   5         int x = 42;
   6         int *p = NULL;
   7         printf("pid[0x%x] ppid[0x%x]\n", getpid(), getppid());
-> 8         *p = x;  // Intentional crash
   9         return 0;
   10    }
(lldb)

### CODE REVIEW

**Review by DhruvSrivastavaX — APPROVED** [review]

File: lldb/source/Plugins/Process/aix-core/AIXCore.cpp [hunk 1]
```diff
@@ -106,6 +106,12 @@ bool AIXCore64Header::ParseCoreHeader(lldb_private::DataExtractor &data,
 
     *offset += 104;
     lldb::offset_t offset_to_user = (*offset + sizeof(ThreadContext64));
+    // This offset calculation is due to the difference between
+    // AIX register size and LLDB register variables order.
+    // __context64 does not match RegContext
+    // To be modified
+    lldb::offset_t offset_to_user = (*offset + sizeof(__context64) +
+            sizeof(thrdentry64));
```
Comment (HemangGadhavi) [inline lldb/source/Plugins/Process/aix-core/AIXCore.cpp:114]: what is the difference between this PR and PR https://github.com/DhruvSrivastavaX/lldb-for-aix/pull/90 ?  and its already merged. why we are doing again ?

Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/aix-core/AIXCore.cpp:114]: #90 was merged in release branch
This is the same change in current branch

**Review by HemangGadhavi — APPROVED** [review]

**Review by ananthsureshkumar — APPROVED** [review]
