### PR TITLE
[WATCHPOINT] Watchpoint support for AIX

### LINKED ISSUE #134: Watchpoint Support for AIX
Currently, watchpoint does not work in AIX. This issue is to track the implementation and defects for that.

### PR DESCRIPTION
**Pull request by DhruvSrivastavaX**
**Added support for Hardware watchpoints on AIX to watch variables**
Additional information: AIX watchpoints only supported write watchpoints which are of size 8-bytes and 8 byte aligned. 
AIX ptrace only allows setting 1 hardware watchpoint for a process.

Before fix: 
```
(lldb) watchpoint set variable globalVariable
error: Watchpoint creation failed (addr=0x100002fc8, size=4, variable expression='globalVariable'). 
error: Setting one of the watchpoint resources failed
(lldb) q
```

After fix:
```
# bin/lldb ../tests/watchpoint1
(lldb) target create "../tests/watchpoint1"
Current executable set to '/home/dhruv/LLDB/tests/watchpoint1' (powerpc64).
(lldb) b main
Breakpoint 1: where = watchpoint1`main + 28 at watchpoint1.c:5, address = 0x00000001000008b4
(lldb) r
Process 38404424 launched: '/home/dhruv/LLDB/tests/watchpoint1' (powerpc64)
Process 38404424 stopped
* thread #1, name = 'watchpoint1', stop reason = breakpoint 1.1
      frame #0: 0x00000001000008b4 watchpoint1`main at watchpoint1.c:5
   2     
   3     int main() {
   4     
-> 5         int a = 10;
   6             char ccounter = 65;  // Variable to watch
   7             short scounter = 0;  // Variable to watch
   8             int counter = 0;  // Variable to watch
(lldb) watchpoint set variable counter
Watchpoint created: Watchpoint 1: addr = 0xffffffffffff738 size = 4 state = enabled type = m
    declare @ '/home/dhruv/LLDB/tests/watchpoint1.c:8'
    watchpoint spec = 'counter'
    watchpoint resources:
       #0: addr = 0xffffffffffff738 size = 4
Watchpoint 1 hit:
    
new value: -1159983106
(lldb) c
Process 38404424 resuming

Watchpoint 1 hit:
old value: -1159983106
new value: 0
Process 38404424 stopped
* thread #1, name = 'watchpoint1', stop reason = watchpoint 1
      frame #0: 0x00000001000008d4 watchpoint1`main at watchpoint1.c:9
   6             char ccounter = 65;  // Variable to watch
   7             short scounter = 0;  // Variable to watch
   8             int counter = 0;  // Variable to watch
-> 9             long lcounter = 0;  // Variable to watch
   10        printf("Initial counter: %d\n", counter);
   11    
   12        // Modify the variable multiple times
(lldb) watchpoint list 
Number of supported hardware watchpoints: 1
Current watchpoints:
Watchpoint 1: addr = 0xffffffffffff738 size = 4 state = enabled type = m
    declare @ '/home/dhruv/LLDB/tests/watchpoint1.c:8'
    watchpoint spec = 'counter'
    watchpoint resources:
       #0: addr = 0xffffffffffff738 size = 4
Watchpoint 1 hit:
    old value: -1159983106
new value: 0
(lldb) c
Process 38404424 resuming
Initial counter: 0

Watchpoint 1 hit:
old value: 0
new value: 10
Process 38404424 stopped
* thread #1, name = 'watchpoint1', stop reason = watchpoint 1
      frame #0: 0x0000000100000910 watchpoint1`main at watchpoint1.c:15
   12        // Modify the variable multiple times
   13        for (int i = 0; i < 5; i++) {
   14            counter += 10;  // Change value
-> 15            printf("Counter after iteration %d: %d\n", i, counter);
   16            lcounter += 10;  // Change value
   17            printf("Counter after iteration %d: %ld\n", i, lcounter);
   18            ccounter += 2;  // Change value
(lldb) c
Process 38404424 resuming
Counter after iteration 0: 10
Counter after iteration 0: 10
Counter after iteration 0: C
Counter after iteration 0: 10

Watchpoint 1 hit:
old value: 10
new value: 20
Process 38404424 stopped
* thread #1, name = 'watchpoint1', stop reason = watchpoint 1
      frame #0: 0x0000000100000910 watchpoint1`main at watchpoint1.c:15
   12        // Modify the variable multiple times
   13        for (int i = 0; i < 5; i++) {
   14            counter += 10;  // Change value
-> 15            printf("Counter after iteration %d: %d\n", i, counter);
   16            lcounter += 10;  // Change value
   17            printf("Counter after iteration %d: %ld\n", i, lcounter);
   18            ccounter += 2;  // Change value
(lldb) watchpoint delete 1
1 watchpoints deleted.
(lldb) c
Process 38404424 resuming
Counter after iteration 1: 20
Counter after iteration 1: 20
Counter after iteration 1: E
Counter after iteration 1: 20
Counter after iteration 2: 30
Counter after iteration 2: 30
Counter after iteration 2: G
Counter after iteration 2: 30
Counter after iteration 3: 40
Counter after iteration 3: 40
Counter after iteration 3: I
Counter after iteration 3: 40
Counter after iteration 4: 50
Counter after iteration 4: 50
Counter after iteration 4: K
Counter after iteration 4: 50
Final counter: 50
Final counter: 50
Final counter: 50
Final counter: K
Process 38404424 exited with status = 10 (0x0000000a) 
(lldb) 
```

### CODE REVIEW

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp [hunk 1]
```diff
@@ -554,14 +555,22 @@ void NativeProcessAIX::MonitorSIGTRAP(const WaitStatus status,
...
-
-    MonitorBreakpoint(thread);
-    break;
+  case SIGTRAP: {
+        reg_ctx.ReadRegister(pc_info, pc_value);
+        struct thrdentry64 entry;
+        tid64_t cursor = 0;
+        int count = getthrds64(GetID(), &entry, sizeof(entry), &cursor, 1);
+        if (count <= 0)
+            LLDB_LOG(log, "Failed to fetch thread info");
```
Comment (HemangGadhavi) [inline lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp:565]: if the count <= 0 do we need to proceed further for watchpoint ?

File: lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp [hunk 2]
```diff
@@ -558,15 +562,10 @@ uint32_t NativeRegisterContextAIX_ppc64::SetHardwareWatchpoint(
...
   }
 
-  // Setup control value
-  control_value = watch_flags << 3;
-  control_value |= ((1 << size) - 1) << 5;
-  control_value |= (2 << 1) | 1;
-
   // Iterate over stored watchpoints and find a free wp_index
   wp_index = LLDB_INVALID_INDEX32;
   for (uint32_t i = 0; i < m_max_hwp_supported; i++) {
```
Comment (HemangGadhavi) [inline lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp]: As AIX has just 1 HW watchpoint do we need this for loop ?

File: lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp [hunk 3]
```diff
@@ -611,24 +620,26 @@ bool NativeRegisterContextAIX_ppc64::ClearHardwareWatchpoint(
...
-  m_hwp_regs[wp_index].slot = 0;
+  m_hwp_regs[wp_index].slot_occupied = false;
   m_hwp_regs[wp_index].mode = 0;
+  m_hwp_regs[wp_index].size = 0;
 
   // Ptrace call to update hardware debug registers
-  //FIXME
-  error = NativeProcessAIX::PtraceWrapper(PT_CLEAR/*PPC_PTRACE_DELHWDEBUG*/,
-                                            m_thread.GetID(), 0, tempSlot);
+  error = NativeProcessAIX::PtraceWrapper(PT_WATCH,
```
Comment (HemangGadhavi) [inline lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp:629]: Is this to clear the watchpoint ? if yes then we can modify the comment its says something else

File: lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp [hunk 4]
```diff
@@ -725,15 +764,17 @@ Status NativeRegisterContextAIX_ppc64::WriteHardwareDebugRegs() {
   long ret;
 
   for (uint32_t i = 0; i < m_max_hwp_supported; i++) {
```
Comment (HemangGadhavi) [inline lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp]: same here, do we need for loop ?

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerCommon.cpp [hunk 5]
```diff
@@ -234,7 +234,7 @@ GDBRemoteCommunicationServerCommon::Handle_qHostInfo(
       host_arch.GetMachine() == llvm::Triple::aarch64_be ||
       host_arch.GetMachine() == llvm::Triple::arm ||
       host_arch.GetMachine() == llvm::Triple::armeb || host_arch.IsMIPS() ||
-      host_arch.GetTriple().isLoongArch())
+      host_arch.GetTriple().isPPC64() || host_arch.GetTriple().isLoongArch())
```
Comment (HemangGadhavi) [inline lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerCommon.cpp]: I think here you need isPPC() check only to support the 32bit as well. because 32bit binaries are treated as PPC.

File: lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp (hunk 2 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp]: Yes, I had kept it to allow more watchpoints for later, but most likely aix will not support multiple wps for P10 and onwards as well, so it might be better to remove.

File: lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp (hunk 4 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp]: Yes, I had kept it to allow more watchpoints for later, but most likely aix will not support multiple wps for P10 and onwards as well, so it might be better to remove.

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp [hunk 6]
```diff
@@ -554,14 +555,22 @@ void NativeProcessAIX::MonitorSIGTRAP(const WaitStatus status,
...
-    // this is watchpoint.
-    reg_ctx.ReadRegister(pc_info, pc_value);
-
-    MonitorBreakpoint(thread);
-    break;
+  case SIGTRAP: {
+        reg_ctx.ReadRegister(pc_info, pc_value);
+        struct thrdentry64 entry;
+        tid64_t cursor = 0;
+        int count = getthrds64(GetID(), &entry, sizeof(entry), &cursor, 1);
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp:562]: Are we handling multithreaded env here? Can we use getprocs64 in that case, As i understand multithread is still not supported?

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerCommon.cpp (hunk 5 above)
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerCommon.cpp]: Have we tested watchpoints on 32 and 64bit binaries ?

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp [hunk 7]
```diff
@@ -1833,6 +1842,14 @@ Status NativeProcessAIX::PtraceWrapper(int req, lldb::pid_t pid, void *addr,
       break;
     }
 
+    case PT_QUERY:
+      ptrace64(req, pid, 0, (int)data_size, (int *)data);
+      break;
+
+    case PT_WATCH:
+      ptrace64(req, pid, (long long)addr, (int)data_size, 0);
```
Comment (ananthsureshkumar) [inline lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp:1862]: Pls catpure the results of ptrace when the watchpoint call fails for either invalid parameter or any other scenario . Where are we capturing them ?

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerCommon.cpp (hunk 5 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerCommon.cpp]: Since 32 bit is not merged yet, we'll test it after both the PRs are merged together

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp (hunk 7 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp:1862]: It is happening below in this same function PtraceWrapper and is shown as a log:
```
1870   LLDB_LOG(log, "ptrace({0}, {1}, {2}, {3}, {4})={5:x}", req, pid, addr, data,  
1871            data_size, ret);                                                     
1872                                                                                 
1873   PtraceDisplayBytes(req, data, data_size);                                     
1874                                                                                 
1875   if (error.Fail())                                                             
1876     LLDB_LOG(log, "ptrace() failed: {0}", error);  
```

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp (hunk 6 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp:562]: It is single threaded right now, but we are doing this only to extract the bit which is set when a watchpoint is triggered. The bit is part of the thrdentry which is extracted via getthrds64

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp (hunk 1 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp]: That will be an error case for which I have added a log, but we can actually put an error message or assert.

**Review by Niranjan-bos — APPROVED** [review]

File: lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp (hunk 1 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/AIX/NativeProcessAIX.cpp:565]: That will be an error case for which I have added a log, but since the below check will fail, it will just move on to  treating it as a regular breakpoint. I can put an error message to add more info

File: lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp (hunk 2 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp]: On second thought, shall we keep it this way? it will avoid hardcoded indexes and will loop only based on m_max_hwp_supported

Comment (HemangGadhavi) [reply lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp]: The main question is why loop is required? we can remove loop and direct assign to the m_hwp_regs, 
instead array we can make it simple one variable so no loop no indexes.  

covert array to variable. 
 std::array<DREG, 4> m_hwp_regs; ----> DREG m_hwp_regs;

Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp]: Yaa true, its only purpose is to work on multiple watchpoints, I have just kept it for future reference.

File: lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp (hunk 3 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/AIX/NativeRegisterContextAIX_ppc64.cpp:629]: Done

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerCommon.cpp (hunk 5 above)
Comment (DhruvSrivastavaX) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerCommon.cpp]: Done

**Review by HemangGadhavi — APPROVED** [review]

**Review by ananthsureshkumar — APPROVED** [review]
